// PART 3: Ranger, Rogue, Sorcerer, Warlock, Wizard
module.exports = {
    'Ranger': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Hunter', description_tr: 'Sürülere, devlere veya hızlı hedeflere karşı en ölümcül avcılık tekniklerini kullanan klasik korucular.', features: [{ level: 3, name: "Hunter's Prey", desc_tr: 'Colossus Slayer (yüksek hasar), Horde Breaker (birden fazla hedef) veya Giant Killer (büyük düşmana tepki saldırısı) seçeneklerinden birini al.' }] },
            { name: 'Beast Master', description_tr: 'Vahşi bir hayvan dostla birlikte avlanan, hayvanını büyük güce ulaştıran orman koruyucuları.', features: [{ level: 3, name: "Ranger's Companion", desc_tr: 'Savaşta birlikte hareket eden, HP\'sini paylaştığın sadık bir vahşi hayvan edin.' }, { level: 7, name: 'Exceptional Training', desc_tr: 'Dostun, senin komutunla saldırı yapmak yerine bonus action ile hareket edebilir.' }] },
            { name: 'Gloom Stalker', description_tr: 'Yeraltı ve karanlıklarda faaliyet gösteren, görünmez kılıklı, ilk turda patlama gücüne sahip gölge avcıları.', features: [{ level: 3, name: 'Dread Ambusher', desc_tr: 'İlk combat turunda ekstra hareket hızı ve ekstra saldırı ile gizli saldırın çok daha güçlüdür.' }, { level: 3, name: 'Umbral Sight', desc_tr: 'Darkvision kazanır; seninle bağlı darkvision\'ı olanlar seni karanlıkta göremez.' }] },
            { name: 'Horizon Walker', description_tr: 'Farklı ebatlar ve düzlemler arasında kapı açan, kötülerin planar seferlerini durduran sınır korucuları.', features: [{ level: 3, name: 'Detect Portal', desc_tr: 'Yakınındaki ebat kapılarını hissedersin.' }, { level: 3, name: 'Planar Warrior', desc_tr: 'Saldırılarını güçlü kuvvet (force) hasarına dönüştürebilirsin.' }] },
            { name: 'Monster Slayer', description_tr: 'Özellikle güçlü büyülü canavarları ve iblisleri hedefleyen, onları zayıflatmayı uzmanlaştıran avcılar.', features: [{ level: 3, name: "Hunter's Sense", desc_tr: 'Bir yaratığın bağışıklıklarını ve dirençlerini doğrudan hissedebilirsin.' }, { level: 3, name: 'Slayer\'s Prey', desc_tr: 'Bir hedefe hasar ekleyen özel bir işaret yaparsın; reaktif saldırıyla bile onu durdurabilirsin.' }] },
            { name: 'Fey Wanderer', description_tr: 'Feywild\'ın büyüsünü içinde taşıyan, büyüleyici aura ve kılık değiştirme yetenekleriyle savaşan doğa gezginleri.', features: [{ level: 3, name: 'Dreadful Strikes', desc_tr: 'Silah saldırılarında ekstra psişik hasar eklersin.' }, { level: 3, name: 'Otherworldly Glamour', desc_tr: 'Charm/Fright\'a karşı avantaj kazanırsın; Charisma yeteneklerine Wisdom bonusunu eklersin.' }] },
            { name: 'Swarmkeeper', description_tr: 'Etrafında sürekli hareket eden küçük varlıklar (böcek, yaprak, parıltı) bulutu taşıyan ve bunu silah olarak kullanan doğa bağlantılı korucular.', features: [{ level: 3, name: 'Gathered Swarm', desc_tr: 'Saldırı sonucunda sürü bir düşmanı iter, seni taşır veya saldırıya ekstra hasar ekler.' }] }
        ]
    },
    'Rogue': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Thief', description_tr: 'Hırsızlık, akrobasi ve hız konusunda mükemmelleşmiş klasik soyguncular.', features: [{ level: 3, name: 'Fast Hands', desc_tr: 'Bonus action ile kilit kır, tuzak söndür, eşya kullan veya cep hırsızlığı yap.' }, { level: 3, name: 'Second-Story Work', desc_tr: 'Tırmanma hızın normal hareket hızına eşit olur; koşarken zıplamaları güçlenir.' }] },
            { name: 'Assassin', description_tr: 'Sürprizi avantaja çeviren, ilk turda yıkıcı hasar veren suikastçılar.', features: [{ level: 3, name: 'Bonus Proficiencies', desc_tr: 'Disguise Kit ve Poisoner\'s Kit uzmanlığı kazanırsın.' }, { level: 3, name: 'Assassinate', desc_tr: 'Savaş başlamadan önce saldıran; karşı taraf saldırmadan önce avantajlı vur ve otomatik kritik al.' }] },
            { name: 'Arcane Trickster', description_tr: 'Yanılsamalar ve büyülerle aldatmayı harmanlayan, Sneak Attack\'ı sihirle güçlendiren büyücü hırsızlar.', features: [{ level: 3, name: 'Spellcasting', desc_tr: 'Enchantment ve Illusion ağırlıklı Wizard büyüleri öğrenirsin.' }, { level: 3, name: 'Mage Hand Legerdemain', desc_tr: 'Görünmez Mage Hand ile uzaktan kilit sök, eşya al ve cep hırsızlığı yap.' }] },
            { name: 'Inquisitive', description_tr: 'Her ayrıntıyı fark eden, yalanı sezebilen ve tek saldırıda düşmanı istismar eden dedektif savaşçılar.', features: [{ level: 3, name: 'Ear for Deceit', desc_tr: 'Insight zarlarında 7 veya altı attığında 8 sayar.' }, { level: 3, name: 'Eye for Detail', desc_tr: 'Bonus action ile Perception veya Investigation zarı at.' }, { level: 3, name: 'Insightful Fighting', desc_tr: 'Bonus action ile düşmanı analiz edip zırh bağımsız Sneak Attack uygularsın.' }] },
            { name: 'Mastermind', description_tr: 'Sosyal manipülasyonu silah olarak kullanan, müttefiklerine taktiksel avantaj kazandıran strateji uzmanları.', features: [{ level: 3, name: 'Master of Intrigue', desc_tr: 'İki dil, Disguise Kit, Forgery Kit ve Gaming Set uzmanlığı kazanırsın.' }, { level: 3, name: 'Master of Tactics', desc_tr: 'Help aksiyonunu Bonus Action ile kullanabilirsin ve menzili 30 ft olur.' }] },
            { name: 'Scout', description_tr: 'Ön keşif ve doğada hayatta kalmayı mükemmelleştirmiş, ilk turda yıldırım hızıyla hareket eden izci hırsızlar.', features: [{ level: 3, name: 'Skirmisher', desc_tr: 'Başka biri yanında bitişiksen reaksiyon ile 5 ft kaçabilirsin (fırsat saldırısı olmadan).' }, { level: 3, name: 'Survivalist', desc_tr: 'Nature ve Survival yeteneklerinde uzmanlık kazanırsın.' }] },
            { name: 'Swashbuckler', description_tr: 'Düelloda rakibini dans ettiren, tek başına çalışmayı seven teatral kılıç ustaları.', features: [{ level: 3, name: 'Fancy Footwork', desc_tr: 'Yakın dövüşte saldırdığın düşman sana fırsat saldırısı yapamaz.' }, { level: 3, name: 'Rakish Audacity', desc_tr: 'Yanında dostun olmasa da 1v1 durumlarda Sneak Attack uygulayabilirsin.' }] },
            { name: 'Phantom', description_tr: 'Ölümle yakın bağı kullanan, hayaletlerin güçlerine dokunan ve düşmanların canından güç devşiren ölüm hırsızları.', features: [{ level: 3, name: 'Whispers of the Dead', desc_tr: 'Kısa dinlenmede hayalet seslerden rastgele bir yetenek uzmanlığı kazanırsın.' }, { level: 3, name: 'Wails from the Grave', desc_tr: 'Sneak Attack aynı anda ikinci bir düşmana da nekrotik hasar verir.' }] },
            { name: 'Soulknife', description_tr: 'Psiyonik enerjiyle oluşturduğu zihinsel bıçaklarla savaşan ve zihin kontrolü yapabilen psi hırsızlar.', features: [{ level: 3, name: 'Psionic Power', desc_tr: 'Psionic Energy Dice pool kazanırsın; bunları çeşitli psiyonik güçler için kullanırsın.' }, { level: 3, name: 'Psychic Blades', desc_tr: 'Maddesel olmayan psiyonik bıçaklar oluşturursun; rakipler buna hazırlanıp direnemez.' }] }
        ]
    },
    'Sorcerer': {
        subclass_unlock_level: 1,
        subclasses: [
            { name: 'Draconic Bloodline', description_tr: 'Soyunda ejderha kanı taşıyan, doğuştan element büyüsü yeteneği ve ejderha direncine sahip sihirbazlar.', features: [{ level: 1, name: 'Dragon Ancestor', desc_tr: 'Bir ejderha tipini seç (ateş, buz vb.); o elementin hasarına direnç kazanırsın.' }, { level: 1, name: 'Draconic Resilience', desc_tr: 'Zırhsız AC\'n 13 + DEX olur; ekstra can kazanırsın.' }] },
            { name: 'Wild Magic', description_tr: 'Saf kaotik büyü enerjisi barındıran, kontrol edilemez sihir patlamaları yaşayan tahmin edilemez büyücüler.', features: [{ level: 1, name: 'Wild Magic Surge', desc_tr: 'Büyü attıktan sonra DM bir d20 atar; 1 gelirse rastgele kaotik bir etki patlak verir.' }, { level: 1, name: 'Tides of Chaos', desc_tr: 'Bir saldırı, yetenek testi veya kurtarma atışına önceden Advantage kazandırabilirsin.' }] },
            { name: 'Divine Soul', description_tr: 'Soyunda ilahi bir dokunuş barındıran, hem sihirbaz hem de rahip listesinden büyü kullanan kutsal büyücüler.', features: [{ level: 1, name: 'Divine Magic', desc_tr: 'Cleric büyü listesine erişim kazanırsın; büyülerinden biri her zaman Bless veya Bane\'dir.' }, { level: 1, name: 'Favored by the Gods', desc_tr: 'Günde 1 kez başarısız bir saldırı veya kurtarma atışına 2d4 ekleyebilirsin.' }] },
            { name: 'Shadow Magic', description_tr: 'Shadowfell\'in karanlığından güç devşiren, karanlıkta görünmez olan ve gölge köpekleri çağıran sihirbazlar.', features: [{ level: 1, name: 'Superior Darkvision', desc_tr: '120 ft darkvision kazanırsın.' }, { level: 1, name: 'Strength of the Grave', desc_tr: 'HP\'n 0\'a düşünce Charisma kurtarma atışıyla ayakta kalabilirsin.' }] },
            { name: 'Storm Sorcery', description_tr: 'Fırtına ve yıldırımın kudretini soyundan getiren, tüm havanın efendisi olan elektrikli sihirbazlar.', features: [{ level: 1, name: 'Wind Speaker', desc_tr: 'Primordial dilini (Air lehçesi Auran dahil) konuşursun.' }, { level: 1, name: 'Tempestuous Magic', desc_tr: 'Büyü attıktan sonra Bonus Action ile 10 ft uçarak hareket edebilirsin.' }] },
            { name: 'Aberrant Mind', description_tr: 'Uzay ötesi varlıklarla zihinsel temas kuran, psişik güçlere sahip klazık sihirbazlar.', features: [{ level: 1, name: 'Psionic Spells', desc_tr: 'Psişik ve algıyla bağlantılı büyülere otomatik erişim kazanırsın.' }, { level: 1, name: 'Telepathic Speech', desc_tr: 'Gördüğün bir canlıyla telepatik konuşma kurabilirsin.' }] },
            { name: 'Clockwork Soul', description_tr: 'Evrenin düzenini ve yasasını temsil eden mekanik güzellikteki sihirbazlar; kaos ve şansı düzeltirler.', features: [{ level: 1, name: 'Clockwork Spells', desc_tr: 'Koruma ve zaman/düzen büyülerine otomatik erişim kazanırsın.' }, { level: 1, name: 'Restore Balance', desc_tr: 'Avantaj veya dezavantaj zarını iptal ederek sıradan bir zar atmalarını sağlarsın.' }] },
            { name: 'Lunar Sorcery', description_tr: 'Ayın büyüsel döngüsünden (yeni ay, dolunay, hilalin) güç kazanan ve her aşamada farklı yetenekler geliştiren sihirbazlar.', features: [{ level: 1, name: 'Moon Fire', desc_tr: 'Sacred Flame cantrip\'i, dolunay aşamasında 2 hedefe etkili olabilir.' }, { level: 1, name: 'Lunar Embodiment', desc_tr: 'Yeni Ay (illusion), Tam Ay (saldırı) ve Hilal (abjuration) aşamasında farklı büyülere erişirsin.' }] }
        ]
    },
    'Warlock': {
        subclass_unlock_level: 1,
        subclasses: [
            { name: 'The Archfey', description_tr: 'Feywild\'ın güçlü bir peri varlığıyla anlaşan, büyüleyici cazibe ve illüzyon güçleri taşıyan büyücüler.', features: [{ level: 1, name: 'Fey Presence', desc_tr: 'Seni çevreleyen peri aurası etraftakileri büyüler veya korkutur.' }] },
            { name: 'The Fiend', description_tr: 'Cehennemden bir şeytanla anlaşan, ateş ve patlama büyüleri kullanan karanlık güç sihirbazları.', features: [{ level: 1, name: "Dark One's Blessing", desc_tr: 'Bir düşmanı öldürdüğünde Charisma + Warlock seviyesi kadar geçici can kazanırsın.' }] },
            { name: 'The Great Old One', description_tr: 'Uzay ötesi, anlaşılmaz varlıklarla pakt yapan psişik güçlere sahip, zihni okuyan ve okunan büyücüler.', features: [{ level: 1, name: 'Awakened Mind', desc_tr: 'Seninle 30 ft içindeki canlıyla dil engeli olmaksızın telepatik konuşabilirsin.' }] },
            { name: 'The Celestial', description_tr: 'Cennet ile bağlantılı bir varlıkla anlaşan, hem hasar hem iyileştirme yapan ışıklı pakt sihirbazları.', features: [{ level: 1, name: 'Healing Light', desc_tr: 'Bir bonus action havuzundan can iyileştirebilirsin (1d6 x Warlock seviyesi pool).' }] },
            { name: 'The Hexblade', description_tr: 'Gölge alanından kaynaklanan güçlü büyülü bir silahla anlaşan, yakın dövüşte de son derece etkili sihirbazlar.', features: [{ level: 1, name: 'Hexblade\'s Curse', desc_tr: 'Bir hedefe lanet at; ona kritik zarı genişletilmiş vurursun ve vurursan can kazanırsın.' }, { level: 1, name: 'Hex Warrior', desc_tr: 'Martial silah uzmanlığı kazanır ve bir silahta Charisma ile saldırırsın.' }] },
            { name: 'The Fathomless', description_tr: 'Okyanusun derinliklerindeki bilinmez bir varlıkla pakt yapan su ve soğuk büyülere sahip derin deniz büyücüleri.', features: [{ level: 1, name: 'Tentacle of the Deeps', desc_tr: 'Bonus action ile büyülü tentakel çağırırsın; düşmanları yavaşlatır ve kışkırtır.' }, { level: 1, name: 'Gift of the Sea', desc_tr: 'Yüzme hızı ve su altında nefes alma kazanırsın.' }] },
            { name: 'The Undying', description_tr: 'Ölümü yenmiş ölümsüz bir varlıkla anlaşan ve neredeyse ölümsüzleşen karanlık sihirbazlar.', features: [{ level: 1, name: 'Among the Dead', desc_tr: 'Spare the Dying cantrip\'ini öğrenirsin; ölümsüzler seni bariz bir neden olmaksızın saldırmak istemez.' }] },
            { name: 'The Genie', description_tr: 'Dao, Djinn, Efreeti veya Marid gibi güçlü bir cin patronuyla anlaşan, cin türüne göre element güçleri kazanan sihirbazlar.', features: [{ level: 1, name: "Genie's Vessel", desc_tr: 'Cin türüne özel bir şişe veya lamba kazanırsın; Long Rest içinde o kaba girebilirsin.' }, { level: 1, name: 'Bottled Respite', desc_tr: 'Kabın içine girerek kısa bir güvenli mola yapabilirsin.' }] },
            { name: 'The Undead', description_tr: 'Dracula veya lich benzeri güçlü ölümsüz bir varlıkla pakt yapan, ölümün sırrına erişmiş karanlık büyücüler.', features: [{ level: 1, name: 'Form of Dread', desc_tr: 'Ölüm görünümüne bürünerek geçici can, Frighten bağışıklığı ve düşmanı korkutma kazanırsın.' }] }
        ]
    },
    'Wizard': {
        subclass_unlock_level: 2,
        subclasses: [
            { name: 'School of Abjuration', description_tr: 'Savunma, kovma ve nötralize etme büyülerinde uzmanlaşmış koruma büyücüleri.', features: [{ level: 2, name: 'Abjuration Savant', desc_tr: 'Koruma büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Arcane Ward', desc_tr: 'Koruma büyüsü okuyunca bir can kalkanı oluşur; hasar önce bunu harcar.' }] },
            { name: 'School of Conjuration', description_tr: 'Varlıkları ve nesneleri çağırma veya teleport büyülerinde uzmanlaşmış çağırma büyücüleri.', features: [{ level: 2, name: 'Conjuration Savant', desc_tr: 'Çağırma büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Minor Conjuration', desc_tr: 'Küçük, gerçekçi olmayan nesneler yaratabilirsin.' }] },
            { name: 'School of Divination', description_tr: 'Geleceği gören, gizlileri keşfeden ve zarları manipüle eden kehanet büyücüleri.', features: [{ level: 2, name: 'Divination Savant', desc_tr: 'Kehanet büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Portent', desc_tr: 'Her gün long rest sonrası 2 portent zarı at; bunları herhangi bir zarın yerine (lehinize veya aleyhinize) kullanabilirsin.' }] },
            { name: 'School of Enchantment', description_tr: 'Zihinleri kontrol ederek düşmanları büyüleyen veya dostlarını güçlendiren büyüleme ustaları.', features: [{ level: 2, name: 'Enchantment Savant', desc_tr: 'Büyüleme büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Hypnotic Gaze', desc_tr: 'Bonus action ile bir düşmanı gözünle büyülersin; hareket edemez ve saldıramaz.' }] },
            { name: 'School of Evocation', description_tr: 'Alan vurucu element büyülerini mükemmelleştiren, dostlarını hasardan koruyabilen yıkım büyücüleri.', features: [{ level: 2, name: 'Evocation Savant', desc_tr: 'Yıkım büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Sculpt Spells', desc_tr: 'Alan büyüleri atarken içindeki dostların kurtarma atışı olmadan hasar almamasını sağlarsın.' }] },
            { name: 'School of Illusion', description_tr: 'Yanılsamaları gerçekmiş gibi kullanan, savaş alanını görsel karmaşaya boğan psiko-büyücüler.', features: [{ level: 2, name: 'Illusion Savant', desc_tr: 'Yanılsama büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Improved Minor Illusion', desc_tr: 'Minor Illusion cantrip\'i aynı anda hem ses hem görüntü oluşturabilir.' }] },
            { name: 'School of Necromancy', description_tr: 'Ölüleri yönlendiren ve hayat enerjisini toplayan karanlık nekromantlar.', features: [{ level: 2, name: 'Necromancy Savant', desc_tr: 'Nekromansi büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Grim Harvest', desc_tr: 'Büyünle birini öldürdüğünde büyünün seviyesi x 2 (veya x 3 cantrip ise) kadar can kazanırsın.' }] },
            { name: 'School of Transmutation', description_tr: 'Maddeyi ve canlıları dönüştüren, kurşunu altına çeviren ve bazen iyileştiren simyacı büyücüler.', features: [{ level: 2, name: 'Transmutation Savant', desc_tr: 'Dönüştürme büyüsü kopyalama masrafı yarıya düşer.' }, { level: 2, name: 'Minor Alchemy', desc_tr: 'Kısa süreliğine bir maddeyi başka bir maddeye dönüştürebilirsin (ahşap → taş vb.).' }] },
            { name: 'Bladesinging', description_tr: 'Kılıç ve büyüyü zarif bir dans içinde birleştiren, AD\'yi büyü kanalıyla artıran Elf büyücüler.', features: [{ level: 2, name: 'Training in War and Song', desc_tr: 'Hafif zırh, bir martial silah uzmanlığı ve Performance uzmanlığı kazanırsın.' }, { level: 2, name: 'Bladesong', desc_tr: 'Bonus action ile Bladesong aktive edersin; hız, AC, konsantrasyon ve Acrobatics\'e Intelligence modifier kadar bonus kazanırsın.' }] },
            { name: 'War Magic', description_tr: 'Savunma ve saldırıyı eş zamanlı yürüten, büyü-zırh uyumunda mükemmelleşmiş savaş büyücüleri.', features: [{ level: 2, name: 'Arcane Deflection', desc_tr: 'Saldırı veya kurtarma atışı için reaksiyon olarak +2/+4 bonus kazanırsın (sınırlı büyü kısıtlamasıyla).' }, { level: 2, name: 'Tactical Wit', desc_tr: 'Initiative zarlarına Intelligence modifier\'ı eklersin.' }] },
            { name: 'Order of Scribes', description_tr: 'Büyü kitabını canlı bir varlık olarak uyandıran, büyülerini anlık değiştirebilen akademisyen büyücüler.', features: [{ level: 2, name: 'Awakened Spellbook', desc_tr: 'Büyü kitabın sihirli bir varlık kazanır; her uzun dinlenmede serbest Wizard cantrip öğrenebilirsin.' }, { level: 2, name: 'Manifest Mind', desc_tr: 'Büyü kitabından yayılan zihinsel bir uzantı ile büyü atabilirsin.' }] },
            { name: 'Graviturgy Magic', description_tr: 'Yerçekimini manipüle ederek düşmanları iter, çeker veya ağırlaştıran Exandria dünyasına ait büyücüler.', features: [{ level: 2, name: 'Adjust Density', desc_tr: 'Bir nesneyi veya canlıyı ağırlaştırıp yavaşlatırsın ya da hafifleştirip yükseltirsin.' }] },
            { name: 'Chronurgy Magic', description_tr: 'Zamanın akışını manipüle eden, zarları geri alan ve hasımları zamana sabitleyen Exandria büyücüleri.', features: [{ level: 2, name: 'Chronal Shift', desc_tr: 'Bir saldırı, yetenek veya kurtarma zarını yeniden attırabilirsin (ister lehine ister aleyhinize).' }, { level: 2, name: 'Temporal Awareness', desc_tr: 'Initiative zarlarına Intelligence modifier\'ı eklersin.' }] }
        ]
    }
};
