// PART 2: Druid, Fighter, Monk, Paladin
module.exports = {
    'Druid': {
        subclass_unlock_level: 2,
        subclasses: [
            { name: 'Circle of the Land', description_tr: 'Belirli bir coğrafyayla (orman, çöl, tundra vb.) bağ kuran ve o bölgenin büyülerini doğuştan bilen büyücü druidler.', features: [{ level: 2, name: 'Natural Recovery', desc_tr: 'Kısa dinlenmede büyü slotlarının bir kısmını yenileyebilirsin.' }, { level: 2, name: 'Bonus Cantrip', desc_tr: 'Fazladan 1 druid cantripi öğrenirsin.' }] },
            { name: 'Circle of the Moon', description_tr: 'Wild Shape dönüşümlerini savaş için mükemmelleştirmiş, ayı veya dev kartal formlarına giren güçlü form değiştiriciler.', features: [{ level: 2, name: 'Combat Wild Shape', desc_tr: 'Wild Shape\'e Bonus Action ile girersin ve formdayken slotları kullanarak can iyileştirirsin.' }, { level: 2, name: 'Circle Forms', desc_tr: 'Dönüşebileceğin hayvanların Challenge Rating limiti büyük ölçüde artar.' }] },
            { name: 'Circle of Dreams', description_tr: 'Feywild\'ın iyimser enerjisinden güç alan, rüyalar ve uykuyla bağlantılı iyileştirici druidler.', features: [{ level: 2, name: 'Balm of the Summer Court', desc_tr: 'Her gün Druid seviyene eşit dice pool kazanırsın; bunları müttefikleri iyileştirmek için harcarsin.' }] },
            { name: 'Circle of the Shepherd', description_tr: 'Doğanın duhalarıyla (spirit) anlaşarak müttefiklerine aura koruması sağlayan ve çağırma (conjuration) büyülerini uzmanlaştıran druidler.', features: [{ level: 2, name: 'Speech of the Woods', desc_tr: 'Sylvan dilini öğrenirsin ve hayvanlarla konuşabilirsin.' }, { level: 2, name: 'Spirit Totem', desc_tr: 'Bonus action ile yakınına Bear, Hawk veya Unicorn ruhunu çağırırsın; her biri farklı bonus sağlar.' }] },
            { name: 'Circle of Spores', description_tr: 'Çürüme ve yeniden doğuşu kutsal sayan, zehirli mantarlarla ve ölümsüz mini-ordusuyla savaşan karanlık druidler.', features: [{ level: 2, name: 'Halo of Spores', desc_tr: 'Sana yaklaşan ya da başlayan canlılara nekrotik hasar veren mantar bulutu oluşturursun.' }, { level: 2, name: 'Symbiotic Entity', desc_tr: 'Wild Shape slotlarını kullanarak geçici can ve güçlü mantar patlamaları kazanırsın.' }] },
            { name: 'Circle of Stars', description_tr: 'Yıldız yollarını (constellations) harita olarak kullanan, kehanet güçleri olan kadim gök bilgini druidler.', features: [{ level: 2, name: 'Star Map', desc_tr: 'Belirli büyüleri hazırlamana gerek kalmaz ve Guidance cantrip\'i kazanırsın.' }, { level: 2, name: 'Starry Form', desc_tr: 'Wild Shape slotunu kullanarak Archer (serbest ışık saldırısı), Chalice (iyileştirme) veya Dragon (konsantrasyon) yıldız formuna girersin.' }] },
            { name: 'Circle of Wildfire', description_tr: 'Yangının yok edici gücünü değil, yeniden büyüme döngüsünü kutsal sayan, alev ile hem iyileştiren hem yakan druidler.', features: [{ level: 2, name: 'Summon Wildfire Spirit', desc_tr: 'Wild Shape slotunu kullanarak savaşta yardımcı olan bir alev ruhu çağırırsın.' }, { level: 2, name: 'Enhanced Bond', desc_tr: 'Wildfire Spirit\'in yakınında ateş veya iyileştirme büyüleri daha güçlü çalışır.' }] }
        ]
    },
    'Fighter': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Champion', description_tr: 'Ham fiziksel mükemmeliyeti hedefleyen, kritik vuruşlarını sıklaştıran ve iyileşme kapasitesini artıran saf savaşçılar.', features: [{ level: 3, name: 'Improved Critical', desc_tr: '20 yerine 19-20 zarında kritik vuruş yaparsın.' }] },
            { name: 'Battle Master', description_tr: 'Zeka gerektiren savaş manevralarıyla rakiplerini kontrol eden, superiority dice kullanan taktik komutanlar.', features: [{ level: 3, name: 'Combat Superiority', desc_tr: '4 adet d8 Superiority Dice ve 3 manevra (silahsızlandırma, itme, yere serme vb.) kazanırsın.' }, { level: 3, name: 'Student of War', desc_tr: 'Bir Artisan aletinde uzmanlık kazanırsın.' }] },
            { name: 'Eldritch Knight', description_tr: 'Hem zırh ve silahla hem de Wizard büyüleriyle savaşan ve silahını bedenine mühürleyen sihirli şövalyeler.', features: [{ level: 3, name: 'Spellcasting', desc_tr: 'Abjuration ve Evocation ağırlıklı Wizard büyüleri öğrenirsin.' }, { level: 3, name: 'Weapon Bond', desc_tr: 'Silahını kendine telepatik olarak bağlarsın; silah eline geri döner ve düşürülemez.' }] },
            { name: 'Arcane Archer', description_tr: 'Okları büyüyle doluşturan, düşmanları yavaşlatan veya kontrol eden gizem okçuları.', features: [{ level: 3, name: 'Arcane Shot', desc_tr: 'Atışlarınla birlikte Banishing, Bursting veya Seeking gibi özel büyüsel efektler tetikleyebilirsin.' }, { level: 3, name: 'Arcane Shot Options', desc_tr: 'Long rest başına 2 kez Arcane Shot kullanabilirsin.' }] },
            { name: 'Cavalier', description_tr: 'Binitten (at veya başka araç) savaşmayı mükemmelleştirmiş, müttefiklerini koruyan atölye savaşçıları.', features: [{ level: 3, name: 'Bonus Proficiency', desc_tr: 'Hayvan Yönetimi, Tarih, İçgüdü, Gözlem veya Performans\'ta uzmanlık kazanırsın.' }, { level: 3, name: 'Born to the Saddle', desc_tr: 'Biniten düşmek zor, atlamak kolay; mount\'a binmek bonus action sayılır..' }] },
            { name: 'Samurai', description_tr: 'Azimli kararlılık ve güçlü savaş ruhuyla hareket eden, düşmanları hızlı ve kesin darbelerle alt eden savaşçılar.', features: [{ level: 3, name: 'Bonus Proficiency', desc_tr: 'Bir dil veya History, Insight, Performance, Persuasion\'da uzmanlık kazanırsın.' }, { level: 3, name: 'Fighting Spirit', desc_tr: 'Bonus action ile kendine geçici can ve sonraki saldırılara avantaj kazandırırsın.' }] },
            { name: 'Psi Warrior', description_tr: 'Psiyonik enerjiyle silahlarını güçlendiren ve zihinsel kalkanlara sahip savaşçılar.', features: [{ level: 3, name: 'Psionic Power', desc_tr: 'Psionic Energy dice pool kazanırsın; bunlarla saldırı zarına bonus ekler, hasar dönüştürür veya zihin kalkanı kurarsın.' }] },
            { name: 'Echo Knight', description_tr: 'Alternatif bir boyuttan "Yankı" kopyasını çağırarak hem hücum hem kaçış yapabilen boyutlararası savaşçılar.', features: [{ level: 3, name: 'Manifest Echo', desc_tr: 'Savaşta sana bağlı bir yankı kopyası (ghost) oluşturursun; onun konumundan saldırabilirsin.' }, { level: 3, name: 'Unleash Incarnation', desc_tr: 'Yankı konumundan ekstra saldırı yaparsın.' }] },
            { name: 'Rune Knight', description_tr: 'Dev medeniyetinin rünlerini silahlarına ve zırhlarına işleyen, dev boyutuna büyüyebilen savaşçılar.', features: [{ level: 3, name: 'Bonus Proficiency', desc_tr: 'Smith\'s Tools ustası ve Giant dilini öğrenirsin.' }, { level: 3, name: 'Rune Carver', desc_tr: 'Cloud, Stone, Hill veya Frost gibi runları öğrenirsin; her biri pasif ve aktif güç verir.' }] },
            { name: 'Purple Dragon Knight (Banneret)', description_tr: 'Liderlik ve ilham yeteneğiyle müttefiklerini rallyleyen komutan savaşçılar.', features: [{ level: 3, name: 'Rallying Cry', desc_tr: 'Second Wind kullandığında etrafındaki 3 müttefikin de can kazanmasını sağlarsın.' }] }
        ]
    },
    'Monk': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Way of the Open Hand', description_tr: 'Silahsız dövüşü kemale erdiren, rakiplerini zemine seren veya ezerken iç huzuru arayan kaid ustalar.', features: [{ level: 3, name: 'Open Hand Technique', desc_tr: 'Flurry of Blows saldırılarında düşmanı yere serebilir, items, itebilir veya reaksiyonunu iptal edebilirsin.' }, { level: 6, name: 'Wholeness of Body', desc_tr: 'Günde bir kez uzun dinlenme gerekmeden 3 x seviye kadar can iyileştir.' }] },
            { name: 'Way of Shadow', description_tr: 'Karanlıkta saklanmayı ve suikastı ön plana çıkaran ninja benzeri gölge ustalar.', features: [{ level: 3, name: 'Shadow Arts', desc_tr: 'Ki ile Darkness, Darkvision, Pass Without Trace ve Silence büyülerini atabilirsin.' }, { level: 6, name: 'Shadow Step', desc_tr: 'Karanlıktan karanlığa 60 ft teleport yapabilir ve avantajlı saldırabilirsin.' }] },
            { name: 'Way of the Four Elements', description_tr: 'Ateş, su, hava ve toprağın elementlerini Ki yoluyla manipüle ederek savaşan elementalist keşişler.', features: [{ level: 3, name: 'Elemental Attunement', desc_tr: 'Küçük elementel etkileri (alev oluşturma, suyu itme vb.) serbest olarak yaratırsın.' }, { level: 3, name: 'Disciple of the Elements', desc_tr: 'Fireball, Wall of Water, Thunderwave benzeri element büyülerini Ki harcayarak atarsın.' }] },
            { name: 'Way of the Sun Soul', description_tr: 'Ki enerjisini görünür güneş ışığına ve alev toplarına dönüştürebilen güneş keşişleri.', features: [{ level: 3, name: 'Radiant Sun Bolt', desc_tr: 'Işınsaldırı olarak güneş ışınsal hasar vurursun; bu saldırıyı Flurry of Blows ile birleştirebilirsin.' }, { level: 6, name: 'Searing Arc Strike', desc_tr: 'Burning Hands büyüsünü Ki harcayarak atarsın.' }] },
            { name: 'Way of the Drunken Master', description_tr: 'Sarhoş görünerek tahmin edilemez, kaotik dövüş hareketleriyle düşmanını yanıltan keşişler.', features: [{ level: 3, name: 'Bonus Proficiencies', desc_tr: 'Performer uzmanlığı ve brewer\'s supplies aletinde yeterlilik kazanırsın.' }, { level: 3, name: 'Drunken Technique', desc_tr: 'Flurry of Blows kullandığında Disengage ve hareket bonusu kazanırsın.' }] },
            { name: 'Way of the Kensei', description_tr: 'Belirli silahları ki enerjisiyle uzantı olarak kullanan, silah sanatının zirvesine ulaşmış keşişler.', features: [{ level: 3, name: 'Path of the Kensei', desc_tr: 'Belirli silahları rahip silahı (monk weapon) olarak belirler ve onlara ekstra saldırı veya hasar kazandırırsın.' }] },
            { name: 'Way of the Long Death', description_tr: 'Ölümün gizemini çalışarak ölüme yaklaşıldıkça güç kazanan ve ölümsüzlüğü araştıran karanlık keşişler.', features: [{ level: 3, name: 'Touch of Death', desc_tr: 'Düşmanı öldürdüğünde seviyene eşit geçici can kazanırsın.' }, { level: 6, name: 'Hour of Reaping', desc_tr: 'Bakışınla etrafındaki canlıları korkutabilirsin.' }] },
            { name: 'Way of the Astral Self', description_tr: 'Ruhsal astral bedenini dışa yansıtarak dev kollar ve gözlerle savaşan aydınlanmış keşişler.', features: [{ level: 3, name: 'Arms of the Astral Self', desc_tr: 'Ki harcayarak astral kollar çıkarırsın; Wisdom ile saldırırsın ve menzil uzar.' }] },
            { name: 'Way of Mercy', description_tr: 'Hem iyileştirici hem de acı çekmeyi bitiren ölümcül dokunuşlara sahip, gizemleri maskeli tabip keşişler.', features: [{ level: 3, name: 'Implements of Mercy', desc_tr: 'Medicine uzmanlığı, Herbalism Kit ve Insight kazanırsın.' }, { level: 3, name: 'Hand of Healing/Harm', desc_tr: 'Ki harcayarak birini iyileştirir veya nekrotik hasar vererek hastalık yayarsın.' }] },
            { name: 'Way of the Ascendant Dragon', description_tr: 'Ejderha soyundan güç alarak nefes saldırısı kazanan ve ejderha görünümü edinen keşişler.', features: [{ level: 3, name: 'Draconic Disciple', desc_tr: 'Ejderha dilini öğrenirsin; silahsız saldırıların asit, ateş, soğuk, şimşek veya zehir hasarına dönüşebilir.' }, { level: 3, name: 'Breath of the Dragon', desc_tr: 'Ki harcayarak ejderha nefesi saldırısı yaparsın.' }] }
        ]
    },
    'Paladin': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Oath of Devotion', description_tr: 'Klasik iyi huylu şövalyenin andıdır. Dürüstlüğe, cesarete ve korumaya adanmış, kutsal enerjiyle dolu savaşçılar.', features: [{ level: 3, name: 'Sacred Weapon', desc_tr: 'Silahına kutsal güç yükler; Charisma modifier kadar saldırı bonusu ve ışık efekti kazandırırsın.' }, { level: 3, name: 'Turn the Unholy', desc_tr: 'İblisleri ve ölümsüzleri 1 dakika boyunca senden kaçmaya zorlarsın.' }] },
            { name: 'Oath of the Ancients', description_tr: 'Işığı, yaşamı ve doğayı korumayı yemin eden eski ritüel şövalyeler; kısmen druid gibi çalışırlar.', features: [{ level: 3, name: 'Nature\'s Wrath', desc_tr: 'Bitki kökleriyle bir düşmanı yakalayarak Restrained yaparsın.' }, { level: 3, name: 'Turn the Faithless', desc_tr: 'Peri varlıklarını ve iblisleri senden kaçmaya zorlarsın.' }] },
            { name: 'Oath of Vengeance', description_tr: 'Büyük kötülüklere karşı amansız ceza vermeye yemin eden, hedefini kilit altına alan karanlık intikamcılar.', features: [{ level: 3, name: 'Vow of Enmity', desc_tr: '1 hedefe düşmanlık yemini et; 1 dakika süresince o hedefe avantajlı saldırırsın.' }, { level: 3, name: 'Abjure Enemy', desc_tr: 'Korku salarak düşmanın hızını sıfırla veya büyük oranda kısıtla.' }] },
            { name: 'Oath of Conquest', description_tr: 'Zaferi, korku yoluyla kontrol etmeyi ve düşmanları sindirmeyi hedefleyen, kötüye yakın despotik şövalyeler.', features: [{ level: 3, name: 'Conquering Presence', desc_tr: 'Etrafındaki düşmanlara korku salarsın.' }, { level: 3, name: 'Guided Strike', desc_tr: 'Kaçırılan saldırı zarına +10 bonus eklersin.' }] },
            { name: 'Oath of Redemption', description_tr: 'Şiddetten kaçınan, her düşmanı ıslah etmeye çalışan ve koruyucu aura ile hasar emerek dostlarını koruyan şövalyeler.', features: [{ level: 3, name: 'Emissary of Peace', desc_tr: 'Persuasion zarlarına +5 bonus.' }, { level: 3, name: 'Rebuke the Violent', desc_tr: 'Bir müttefikin zarar görmesine tepki olarak saldırgana aynı hasarı yansıtırsın.' }] },
            { name: 'Oath of Glory', description_tr: 'Destansı kahramanlığı ve olimpik yüceliği hedefleyen, müttefiklerini ilham vererek destekleyen yarı-tanrı şövalyeler.', features: [{ level: 3, name: 'Inspiring Smite', desc_tr: 'Divine Smite kullandıktan sonra başkalarına geçici can dağıtabilirsin.' }, { level: 3, name: 'Peerless Athlete', desc_tr: 'Atlet ve güç gerektiren yeteneklere avantaj kazanırsın.' }] },
            { name: 'Oath of the Watchers', description_tr: 'Mortaller'ın dünyasını uzay- ötesi tehditlere(aberration, celestial, fey, fiend) karşı koruyan nöbetçi şövalyeler.', features: [{ level: 3, name: 'Watcher\'s Will', desc_tr: 'Müttefiklerine zihne etki eden büyülere karşı avantaj verirsin.' }, { level: 3, name: 'Abjure the Extraplanar', desc_tr: 'Değişik düzlemden gelen yaratıkları senden kaçmaya zorlarsın.' }] },
{ name: 'Oathbreaker', description_tr: 'Andını çiğneyerek karanlığa düşmüş, ölümsüzleri emreden ve nekrotik güç kullanan düşmüş şövalyeler.', features: [{ level: 3, name: 'Dreadful Aspect', desc_tr: 'Karanlık korku aurası yayarak etraftakileri korkutur.' }, { level: 3, name: 'Channel Divinity: Control Undead', desc_tr: 'Bir ölümsüzü emrin altına alırsın.' }] },
{ name: 'Oath of the Crown', description_tr: 'Medeniyete, yasasına ve ülkesine bağlı, kola kola savaştığı müttefiklerini asla terk etmeyen kahramanlar.', features: [{ level: 3, name: 'Champion Challenge', desc_tr: 'Etrafındaki düşmanları senden uzaklaşmamaya zorlarsın.' }, { level: 3, name: 'Turn the Tide', desc_tr: 'Etrafındaki düşük HP\'li dostlara can yenilemesini sağlarsın.' }] }
        ]
    }
};
