// PART 1: Barbarian, Bard, Cleric
module.exports = {
    'Barbarian': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Path of the Berserker', description_tr: 'Öfkelerini saf vahşete dönüştüren, savaşın ortasında çılgınca bir güç kazanan gözü dönmüş savaşçılar.', features: [{ level: 3, name: 'Frenzy', desc_tr: 'Rage halindeyken bonus action ile ekstra 1 yakın dövüş saldırısı yapabilirsin, ancak öfken bitince 1 seviye Exhaustion alırsın.' }, { level: 6, name: 'Mindless Rage', desc_tr: 'Öfkeliyken büyülü korku ve büyüleme etkilerine karşı bağışıklık kazanırsın.' }] },
            { name: 'Path of the Totem Warrior', description_tr: 'Hayvan ruhlarıyla (Totem) bağ kurarak doğanın vahşi gücünü ve koruyuculuğunu içine çeken savaşçılar.', features: [{ level: 3, name: 'Totem Spirit (Bear)', desc_tr: 'Öfkeliyken psişik hasar hariç tüm hasara karşı direnç kazanırsın.' }, { level: 3, name: 'Totem Spirit (Eagle)', desc_tr: 'Öfkeliyken fırsat saldırılarına karşı dezavantaj uygularsın ve bonus action ile koş.' }, { level: 3, name: 'Totem Spirit (Wolf)', desc_tr: 'Seninle aynı düşmanla bitişik dost varken saldırılara avantaj kazandırsın.' }] },
            { name: 'Path of the Ancestral Guardian', description_tr: 'Atalarının ruhlarını çağırarak savaş alanında hem kendini hem de dostlarını koruyan şamanik savaşçılar.', features: [{ level: 3, name: 'Ancestral Protectors', desc_tr: 'Rage halinde saldırdığın ilk düşman, sana saldırırken dezavantaj alır ve sen dahil diğer hedeflere zarar verirken direnç kazanmazlar.' }, { level: 6, name: 'Spirit Shield', desc_tr: 'Reaksiyon olarak, atalarının ruhlarıyla bir dosta gelen hasarı azaltabilirsin.' }] },
            { name: 'Path of the Storm Herald', description_tr: 'İçlerinde fırtına, çöl kumu ya da buz tufanı gibi bir elementel güç barındıran ve Rage sırasında doğa olaylarını ateşleyen savaşçılar.', features: [{ level: 3, name: 'Storm Aura (Tundra)', desc_tr: 'Rage halinde etrafındaki düşmanlara buz hasarı ve geçici can verir.' }, { level: 3, name: 'Storm Aura (Sea)', desc_tr: 'Rage halinde yıldırım hasarı verip düşmanları geriye itebilir.' }, { level: 3, name: 'Storm Aura (Desert)', desc_tr: 'Rage halinde etrafındaki canlılara ateş hasarı verir.' }] },
            { name: 'Path of the Zealot', description_tr: 'İlahı adına ateşli bir bağlılıkla savaşan ve ölümden geri dönebildiği için neredeyse öldürülemeyen savaşçılar.', features: [{ level: 3, name: 'Divine Fury', desc_tr: 'Rage halindeyken saldırılarında ekstra ışıyan (radiant) veya nekrotik (necrotic) hasar verilir.' }, { level: 3, name: 'Warrior of the Gods', desc_tr: 'Seni hayata döndürecek büyülerin component maliyeti yoktur; tanrılar seni ölüme bırakmaz.' }] },
            { name: 'Path of the Beast', description_tr: 'İçlerindeki canavar ruhunu serbest bırakarak pençe, ısırık ve kuyrukla savaşan vahşi doğa savaşçıları.', features: [{ level: 3, name: 'Form of the Beast', desc_tr: 'Rage halinde iken pençe, ısırık veya kuyruktan birini seçerek doğal silah kazanırsın.' }, { level: 6, name: 'Bestial Soul', desc_tr: 'Yüzme, tırmanma veya atlama konusunda ekstra hareket imkanı kazanırsın.' }] },
            { name: 'Path of Wild Magic', description_tr: 'Kontrol edilmez büyü enerjisi barındıran bedenlerinde Rage sırasında kaotik sihir patlamaları yaşayan savaşçılar.', features: [{ level: 3, name: 'Magic Awareness', desc_tr: 'Yakınındaki aktif büyü veya büyü etkilerini hissedebilirsin.' }, { level: 3, name: 'Wild Surge', desc_tr: 'Rage\'e girince rastgele kaotik büyüsel etkiler ortaya çıkar.' }] },
            { name: 'Path of the Battlerager', description_tr: 'Sivri zırh parçaları giyen ve gövde temasıyla düşmanları kanatan, Cüceler için özel bir savaşçı yol.', features: [{ level: 3, name: 'Battlerager Armor', desc_tr: 'Sivri zırh giydiğinde yakın dövüş saldırılarında ek delici hasar verirsin.' }, { level: 3, name: 'Reckless Attack (Piercing)', desc_tr: 'Wrestle yaptığında bonus action ile sivri zırhla hasar vurabilirsin.' }] }
        ]
    },
    'Bard': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'College of Lore', description_tr: 'Bilgiyi güç olarak kullanan, diğer sınıfların büyülerine bile erişebilen en çok yönlü Ozan okulu.', features: [{ level: 3, name: 'Bonus Proficiencies', desc_tr: 'İstediğin herhangi 3 yetenekte (skill) uzmanlık kazanırsın.' }, { level: 3, name: 'Cutting Words', desc_tr: 'Bardic Inspiration zarını bir düşmanın saldırı, hasar veya yetenek zarından düşebilirsin.' }] },
            { name: 'College of Valor', description_tr: 'Kılıç arkasında şiir söyleyen, cephede savaşan ve müttefiklerine ilham veren savaşçı Ozanlar.', features: [{ level: 3, name: 'Combat Inspiration', desc_tr: 'Dostların Bardic Inspiration zarını saldırı zarına veya AC\'ye ekleyebilir.' }, { level: 3, name: 'Bonus Proficiencies', desc_tr: 'Orta boy zırh, kalkan ve martial silahlarda uzmanlık kazanırsın.' }] },
            { name: 'College of Glamour', description_tr: 'Feywild\'dan güç alan, büyüleyici görünüşü ve sihirli cazibesiyle düşmanları etkisiz kılan Ozanlar.', features: [{ level: 3, name: 'Mantle of Inspiration', desc_tr: 'Bardic Inspiration harcayarak etraftakilere geçici can ver ve onları hareket ettir.' }, { level: 3, name: 'Enthralling Performance', desc_tr: 'Bir dinleticini büyüleyip onun üzerinde etki kur.' }] },
            { name: 'College of Swords', description_tr: 'Bıçak numaraları yapan, savaşı bir gösteri olarak sunan ve kılıcını büyüyle bütünleştiren akrobatik savaşçı Ozanlar.', features: [{ level: 3, name: 'Blade Flourish', desc_tr: 'Saldırı yaptıktan sonra Bardic Inspiration zarını harcayarak AC kazan, saldırı genişlet veya rakibi geri it.' }, { level: 3, name: 'Bonus Proficiencies', desc_tr: 'Orta boy zırh ve scimitar gibi savaş silahlarında uzmanlık kazanırsın.' }] },
            { name: 'College of Whispers', description_tr: 'Topluma sızdıran, dedikodu ve korku yayan, gölgede hareket eden karanlık doğalı casuslar ve suikastçılar.', features: [{ level: 3, name: 'Psychic Blades', desc_tr: 'Bardic Inspiration harcayarak silah saldırına ekstra psişik hasar ekle.' }, { level: 3, name: 'Words of Terror', desc_tr: 'Görüşme sırasında bir insanı korkuya sürükleyecek şeyler fısıldayabilirsin.' }] },
            { name: 'College of Creation', description_tr: 'Dünyanın yaratılışındaki ilk ezgiden güç alan, yoktan eşya yaratan ve müziği kullanarak maddeyi şekillendiren Ozanlar.', features: [{ level: 3, name: 'Note of Potential', desc_tr: 'Bardic Inspiration zarını harcayan müttefikin ekstra avantaj veya etki kazanır.' }, { level: 3, name: 'Animating Performance', desc_tr: 'Bir eşyayı canlandırabilirsin; o eşya savaşta yardımcın olur.' }] },
            { name: 'College of Eloquence', description_tr: 'Kelimenin gücüne hükmeden, her konuşmada mükemmeliyetçi olan ve hiçbir zarı boşa harcamayan retoriğin ustaları.', features: [{ level: 3, name: 'Silver Tongue', desc_tr: 'Persuasion ve Deception zarlarında 9 veya altı attığında 10 saymak olur (Reliable Talent benzeri).' }, { level: 3, name: 'Unsettling Words', desc_tr: 'Bardic Inspiration harcayarak bir düşmanın önündeki kurtarma atışına dezavantaj verirsin.' }] },
            { name: 'College of Spirits', description_tr: 'Öteki dünyanın ruhlarıyla irtibata geçen, tarot ve kehanet yoluyla savaş alanında güç toplayan gizem Ozanları.', features: [{ level: 3, name: 'Guiding Whispers', desc_tr: 'Guidance cantrip\'ini öğrenirsin.' }, { level: 3, name: 'Spiritual Focus', desc_tr: 'Bir spirit odak nesnesi (haritama tahtası, kristal top vb.) büyü odağı olarak kullanabilirsin.' }] }
        ]
    },
    'Cleric': {
        subclass_unlock_level: 1,
        subclasses: [
            { name: 'Life Domain', description_tr: 'İyileştirme ve sağlığa adanmış en güçlü destek ilahi yolu. Müttefikleri ölümden döndürür.', features: [{ level: 1, name: 'Disciple of Life', desc_tr: 'İyileştirme büyülerinde iyileşen can miktarı 2 + büyü seviyesi kadar fazla artar.' }] },
            { name: 'War Domain', description_tr: 'Savaş tanrılarına hizmet eden ve ön safta çarpışan pastoral savaşçı rahipler.', features: [{ level: 1, name: 'War Priest', desc_tr: 'Saldırı yaptıktan sonra bonus action ile 1 silah saldırısı yapabilirsin (WIS mod sayıda).' }] },
            { name: 'Light Domain', description_tr: 'Güneş ve ışığın tanrılarına tapan, alev topları atan ve kötülüğü yakanlar.', features: [{ level: 1, name: 'Warding Flare', desc_tr: 'Sana vuracak bir düşmanın saldırısına dezavantaj verirsin.' }, { level: 1, name: 'Bonus Cantrip', desc_tr: 'Light (Işık) cantrip\'ini öğrenirsin.' }] },
            { name: 'Knowledge Domain', description_tr: 'Bilgeliğin ve bilginin tanrısına tapan, tarihi, dilleri ve sırları bilen rahipler.', features: [{ level: 1, name: 'Blessings of Knowledge', desc_tr: '2 dil ve 2 yetenekte uzmanlık kazanırsın.' }] },
            { name: 'Nature Domain', description_tr: 'Doğa ve vahşi yaşamın ilahilerine hizmet eden, bitki ve hayvanları yönlendiren doğacı rahipler.', features: [{ level: 1, name: 'Acolyte of Nature', desc_tr: '1 druid cantrip ve 1 yetenekte uzmanlık kazanırsın.' }] },
            { name: 'Tempest Domain', description_tr: 'Fırtına ve şimşek tanrılarının gücüyle savaşa atılan, göğü giydiren savaşçı rahibeler.', features: [{ level: 1, name: 'Wrath of the Storm', desc_tr: 'Sana çarpan düşmana reaksiyon olarak şimşek veya gök gürültüsü hasarı verirsin.' }] },
            { name: 'Trickery Domain', description_tr: 'Hile, kaos ve hilekarlık tanrılarına tapan, illüzyonlar ve şekil değiştirmeyle savaşan kurnaz rahipler.', features: [{ level: 1, name: 'Blessing of the Trickster', desc_tr: 'Bir dosta Stealth zarlarında avantaj verebilirsin.' }] },
            { name: 'Death Domain', description_tr: 'Genellikle kötü hizalamalı karakterlerin yolu. Ölüm tanrısının gücüyle nekrotik enerji akıtan rahipler.', features: [{ level: 1, name: 'Reaper', desc_tr: 'Tek hedefli nekrotik cantrip\'ler iki hedefe kadar etki edebilir.' }] },
            { name: 'Arcana Domain', description_tr: 'Büyünün kendisini kutsal sayan, wizard büyülerine erişen ve büyüsel canavarlarla anlaşan rahipler.', features: [{ level: 1, name: 'Arcane Initiate', desc_tr: 'İstediğin 2 wizard cantrip öğrenirsin.' }] },
            { name: 'Forge Domain', description_tr: 'Demircilik ve yaratıcılık tanrısına tapan, silahları ve zırhları kutsal enerjiyle güçlendiren rahipler.', features: [{ level: 1, name: 'Blessing of the Forge', desc_tr: 'Uzun dinlenmede bir silah veya zırha +1 büyüsel bonus verirsin.' }] },
            { name: 'Grave Domain', description_tr: 'Ölüm ve yasın doğal döngüsüne saygı duyan, ölümsüzlere düşman olan rahipler.', features: [{ level: 1, name: 'Circle of Mortality', desc_tr: 'HP\'si 0 olan canlıları iyileştiren büyülerde zarları maksimum al.' }] },
            { name: 'Order Domain', description_tr: 'Düzen, yasa ve medeniyetin tanrısına bağlı, müttefiklerini komuta eden kanun rahipleri.', features: [{ level: 1, name: "Voice of Authority", desc_tr: 'Bir müttefike büyü atınca o müttefik bonus action olarak bir saldırı yapabilir.' }] },
            { name: 'Peace Domain', description_tr: 'Barış, uyum ve anlayışın kutsal yolu. Müttefikler arasında güçlü bağlar kuran destek rahipler.', features: [{ level: 1, name: 'Emboldening Bond', desc_tr: 'Birden fazla dost arasında kutsal bir bağ kurarak onlara zar bonusu verebilirsin.' }] },
            { name: 'Twilight Domain', description_tr: 'Gün batımı, karanlık öncesi ve uykunun ilahisine tapan, geceyi koruyan rahipler.', features: [{ level: 1, name: 'Eyes of Night', desc_tr: 'Gelişmiş karanlık görüşü kazanır ve bunu müttefiklerle paylaşabilirsin.' }, { level: 1, name: 'Vigilant Blessing', desc_tr: 'Bir müttefikin initiative zarına avantaj verirsin.' }] }
        ]
    }
};
