// PART 1: Barbarian, Bard, Cleric
module.exports = {
    'Barbarian': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Path of the Berserker', description_tr: 'Öfkelerini saf vahşete dönüştüren, savaşın ortasında çılgınca bir güç kazanan gözü dönmüş savaşçılar.', features: [{ level: 3, name: 'Frenzy', desc_tr: 'Rage halindeyken Bonus Action ile fazladan bir yakın dövüş saldırısı yapabilirsin. Rage bittiğinde 1 seviye Exhaustion alırsın.' }, { level: 6, name: 'Mindless Rage', desc_tr: 'Rage halindeyken Charmed and Frightened durumlarına karşı bağışıklık kazanırsın.' }] },
            { name: 'Path of the Totem Warrior', description_tr: 'Hayvan ruhlarıyla (Totem) bağ kurarak doğanın vahşi gücünü ve koruyuculuğunu içine çeken savaşçılar.', features: [{ level: 3, name: 'Totem Spirit (Bear)', desc_tr: 'Rage halindeyken Psychic hasar hariç tüm hasar türlerine karşı Resistance kazanırsın.' }, { level: 3, name: 'Totem Spirit (Eagle)', desc_tr: 'Rage halindeyken Opportunity Attack\'lara karşı Disadvantage uygularsın ve Bonus Action ile Dash yapabilirsin.' }, { level: 3, name: 'Totem Spirit (Wolf)', desc_tr: 'Seninle aynı düşmanla bitişik (within 5ft) bir müttefikin varken, o düşmana yapılan yakın dövüş saldırılarına Advantage kazandırırsın.' }] },
            { name: 'Path of the Ancestral Guardian', description_tr: 'Atalarının ruhlarını çağırarak savaş alanında hem kendini hem de dostlarını koruyan şamanik savaşçılar.', features: [{ level: 3, name: 'Ancestral Protectors', desc_tr: 'Rage halindeyken saldırdığın ilk düşman, senden başkasına saldırırken Disadvantage alır ve müttefiklerin o saldırılardan gelen hasara karşı Resistance kazanır.' }, { level: 6, name: 'Spirit Shield', desc_tr: 'Reaction olarak, atalarının ruhlarıyla bir müttefike gelen hasarı [2d6] (seviyeye göre artar) azaltabilirsin.' }] },
            { name: 'Path of the Storm Herald', description_tr: 'İçlerinde fırtına, çöl kumu ya da buz tufanı gibi bir elementel güç barındıran ve Rage sırasında doğa olaylarını ateşleyen savaşçılar.', features: [{ level: 3, name: 'Storm Aura (Tundra)', desc_tr: 'Rage halindeyken etrafındaki müttefiklerine [2] (seviyeye göre artar) Temporary HP verir.' }, { level: 3, name: 'Storm Aura (Sea)', desc_tr: 'Rage halindeyken müttefikine [1d6] (seviye ile artar) Lightning hasarı ile tepki verebilirsin.' }, { level: 3, name: 'Storm Aura (Desert)', desc_tr: 'Rage halindeyken etrafındaki canlılara [2] (seviyeye göre artar) Fire hasarı verir.' }] },
            { name: 'Path of the Zealot', description_tr: 'İlahı adına ateşli bir bağlılıkla savaşan ve ölümden geri dönebildiği için neredeyse öldürülemeyen savaşçılar.', features: [{ level: 3, name: 'Divine Fury', desc_tr: 'Rage halindeyken turun ilk vuruşunda [1d6 + Sv./2] Radiant veya Necrotic hasar verirsin.' }, { level: 3, name: 'Warrior of the Gods', desc_tr: 'Seni hayata döndürecek büyülerin component maliyeti yoktur; tanrılar seni ölüme bırakmaz.' }] },
            { name: 'Path of the Beast', description_tr: 'İçlerindeki canavar ruhunu serbest bırakarak pençe, ısırık ve kuyrukla savaşan vahşi doğa savaşçıları.', features: [{ level: 3, name: 'Form of the Beast', desc_tr: 'Rage\'e girdiğinde Bite, Claws veya Tail seçerek özel bir Natural Weapon kazanırsın.' }, { level: 6, name: 'Bestial Soul', desc_tr: 'Yüzme, tırmanma veya atlama konusunda ekstra hareket imkanı kazanırsın.' }] },
            { name: 'Path of Wild Magic', description_tr: 'Kontrol edilmez büyü enerjisi barındıran bedenlerinde Rage sırasında kaotik sihir patlamaları yaşayan savaşçılar.', features: [{ level: 3, name: 'Magic Awareness', desc_tr: 'Action harcayarak [PB] kez 60ft içindeki büyü varlığını hissedebilirsin.' }, { level: 3, name: 'Wild Surge', desc_tr: 'Rage\'e girdiğinde [1d8] sonucuna göre rastgele bir kaotik büyü etkisi tetiklenir.' }] },
            { name: 'Path of the Battlerager', description_tr: 'Sivri zırh parçaları giyen ve gövde temasıyla düşmanları kanatan, Cüceler için özel bir savaşçı yol.', features: [{ level: 3, name: 'Battlerager Armor', desc_tr: 'Spiked Armor giyerken Bonus Action ile bir yakın dövüş saldırısı yapabilirsin.' }, { level: 3, name: 'Reckless Attack (Piercing)', desc_tr: 'Grapple yaptığında müttefikine veya kendine yakın düşmana [3] Piercing hasarı verirsin.' }] }
        ]
    },
    'Bard': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'College of Lore', description_tr: 'Bilgiyi güç olarak kullanan, diğer sınıfların büyülerine bile erişebilen en çok yönlü Ozan okulu.', features: [{ level: 3, name: 'Bonus Proficiencies', desc_tr: 'İstediğin herhangi 3 Skill için Proficiency kazanırsın.' }, { level: 3, name: 'Cutting Words', desc_tr: 'Reaction olarak, Ozan İlhamı (Bardic Inspiration) zarını bir düşmanın saldırı, hasar veya yetenek zarından düşebilirsin.' }] },
            { name: 'College of Valor', description_tr: 'Kılıç arkasında şiir söyleyen, cephede savaşan ve müttefiklerine ilham veren savaşçı Ozanlar.', features: [{ level: 3, name: 'Combat Inspiration', desc_tr: 'Müttefiklerin Bardic Inspiration zarını hasar zarına veya AC\'sine ekleyebilir.' }, { level: 3, name: 'Bonus Proficiencies', desc_tr: 'Medium Armor, Shield ve Martial Weapon kullanımı için Proficiency kazanırsın.' }] },
            { name: 'College of Glamour', description_tr: 'Feywild\'dan güç alan, büyüleyici görünüşü ve sihirli cazibesiyle düşmanları etkisiz kılan Ozanlar.', features: [{ level: 3, name: 'Mantle of Inspiration', desc_tr: 'Bardic Inspiration harcayarak etrafındakilere [2d6] (seviye ile artar) Temporary HP ver ve onlara Reaksiyonları ile hareket etme imkanı sun.' }, { level: 3, name: 'Enthralling Performance', desc_tr: 'Bir dinleyiciyi büyüleyip onun üzerinde etki kurarsın.' }] },
            { name: 'College of Swords', description_tr: 'Bıçak numaraları yapan, savaşı bir gösteri olarak sunan ve kılıcını büyüyle bütünleştiren akrobatik savaşçı Ozanlar.', features: [{ level: 3, name: 'Blade Flourish', desc_tr: 'Saldırı yaptıktan sonra Bardic Inspiration harcayarak AC kazanabilir, hasar artırabilir veya rakibi itebilirsin.' }, { level: 3, name: 'Bonus Proficiencies', desc_tr: 'Medium Armor ve Scimitar kullanımı için Proficiency kazanırsın.' }] },
            { name: 'College of Whispers', description_tr: 'Topluma sızan, dedikodu ve korku yayan, gölgede hareket eden karanlık doğalı casuslar ve suikastçılar.', features: [{ level: 3, name: 'Psychic Blades', desc_tr: 'Bardic Inspiration harcayarak silah saldırına [2d6] (seviye ile artar) ekstra Psychic hasarı eklersin.' }, { level: 3, name: 'Words of Terror', desc_tr: 'Görüşme sırasında bir kişiyi korkuya sürükleyecek şeyler fısıldayabilirsin.' }] },
            { name: 'College of Creation', description_tr: 'Dünyanın yaratılışındaki ilk ezgiden güç alan, yoktan eşya yaratan ve müziği kullanarak maddeyi şekillendiren Ozanlar.', features: [{ level: 3, name: 'Note of Potential', desc_tr: 'Bardic Inspiration zarını harcayan müttefikin fazladan Advantage veya özel bir etki kazanır.' }, { level: 3, name: 'Animating Performance', desc_tr: 'Action harcayarak bir eşyayı canlandırabilirsin; o eşya seninle birlikte savaşır.' }] },
            { name: 'College of Eloquence', description_tr: 'Kelimenin gücüne hükmeden, her konuşmada mükemmeliyetçi olan ve hiçbir zarı boşa harcamayan retoriğin ustaları.', features: [{ level: 3, name: 'Silver Tongue', desc_tr: 'Persuasion ve Deception zarlarında 9 veya altı attığında zar sonucunu 10 sayarsın (Reliable Talent).' }, { level: 3, name: 'Unsettling Words', desc_tr: 'Bardic Inspiration harcayarak bir düşmanın Saving Throw atışına Disadvantage verirsin.' }] },
            { name: 'College of Spirits', description_tr: 'Öteki dünyanın ruhlarıyla irtibata geçen, tarot ve kehanet yoluyla savaş alanında güç toplayan gizem Ozanları.', features: [{ level: 3, name: 'Guiding Whispers', desc_tr: 'Guidance cantrip\'ini öğrenirsin ve 60ft menzili ile kullanabilirsin.' }, { level: 3, name: 'Spiritual Focus', desc_tr: 'Bir spirit odak nesnesini (kristal top vb.) Spellcasting Focus olarak kullanabilirsin.' }] }
        ]
    },
    'Cleric': {
        subclass_unlock_level: 1,
        subclasses: [
            { name: 'Life Domain', description_tr: 'İyileştirme ve sağlığa adanmış en güçlü destek ilahi yolu. Müttefikleri ölümden döndürür.', features: [{ level: 1, name: 'Disciple of Life', desc_tr: 'Healing Spell kullanınca iyileşen can miktarı 2 + [Level] (büyü seviyesi) kadar artar.' }] },
            { name: 'War Domain', description_tr: 'Savaş tanrılarına hizmet eden ve ön safta çarpışan pastoral savaşçı rahipler.', features: [{ level: 1, name: 'War Priest', desc_tr: 'Saldırı yaptıktan sonra Bonus Action ile fazladan bir silah saldırısı yapabilirsin. Bu özelliği [WIS] kez kullanabilirsin.' }] },
            { name: 'Light Domain', description_tr: 'Güneş ve ışığın tanrılarına tapan, alev topları atan ve kötülüğü yakanlar.', features: [{ level: 1, name: 'Warding Flare', desc_tr: 'Reaction harcayarak sana vurmak isteyen bir düşmanın saldırı zarına Disadvantage uygularsın.' }, { level: 1, name: 'Bonus Cantrip', desc_tr: 'Light cantrip\'ini öğrenirsin.' }] },
            { name: 'Knowledge Domain', description_tr: 'Bilgeliğin ve bilginin tanrısına tapan, tarihi, dilleri ve sırları bilen rahipler.', features: [{ level: 1, name: 'Blessings of Knowledge', desc_tr: 'İki dil öğrenirsin ve seçtiğin iki Skill için Proficiency (ve Expertise) kazanırsın.' }] },
            { name: 'Nature Domain', description_tr: 'Doğa ve vahşi yaşamın ilahilerine hizmet eden, bitki ve hayvanları yönlendiren doğacı rahipler.', features: [{ level: 1, name: 'Acolyte of Nature', desc_tr: '1 Druid cantrip ve 1 Skill (Animal Handling, Nature, veya Survival) için Proficiency kazanırsın. Ayrıca Heavy Armor Proficiency kazanırsın.' }] },
            { name: 'Tempest Domain', description_tr: 'Fırtına ve şimşek tanrılarının gücüyle savaşa atılan, göğü giydiren savaşçı rahibeler.', features: [{ level: 1, name: 'Wrath of the Storm', desc_tr: 'Sana 5ft mesafeden saldıran bir düşmana Reaction harcayarak [2d8] Lightning veya Thunder hasarı verebilirsin.' }] },
            { name: 'Trickery Domain', description_tr: 'Hile, kaos ve hilekarlık tanrılarına tapan, illüzyonlar ve şekil değiştirmeyle savaşan kurnaz rahipler.', features: [{ level: 1, name: 'Blessing of the Trickster', desc_tr: 'Action harcayarak başka bir canlıya Stealth kontrollerinde Advantage verirsin.' }] },
            { name: 'Death Domain', description_tr: 'Genellikle kötü hizalamalı karakterlerin yolu. Ölüm tanrısının gücüyle nekrotik enerji akıtan rahipler.', features: [{ level: 1, name: 'Reaper', desc_tr: 'Tek hedefli Necromancy cantrip\'lerini birbirine yakın iki hedefe birden vuracak şekilde kullanabilirsin.' }] },
            { name: 'Arcana Domain', description_tr: 'Büyünün kendisini kutsal sayan, wizard büyülerine erişen ve büyüsel canavarlarla anlaşan rahipler.', features: [{ level: 1, name: 'Arcane Initiate', desc_tr: 'İki Wizard cantrip\'i öğrenirsin (senin için Cleric büyüsü sayılırlar) ve Arcana Skill için Proficiency kazanırsın.' }] },
            { name: 'Forge Domain', description_tr: 'Demircilik ve yaratıcılık tanrısına tapan, silahları ve zırhları kutsal enerjiyle güçlendiren rahipler.', features: [{ level: 1, name: 'Blessing of the Forge', desc_tr: 'Long Rest bitiminde bir silaha +1 Bonuslu Magic Weapon veya bir zırha +1 Bonuslu Magic Armor özelliklerini geçici olarak verirsin.' }] },
            { name: 'Grave Domain', description_tr: 'Ölüm ve yasın doğal döngüsüne saygı duyan, ölümsüzlere düşman olan rahipler.', features: [{ level: 1, name: 'Circle of Mortality', desc_tr: 'HP\'si 0 olan bir canlıyı iyileştirirken tüm zarları maksimum değerinde kabul edersin. Spare the Dying cantrip\'ini Bonus Action ve 30ft menzil ile kullanabilirsin.' }] },
            { name: 'Order Domain', description_tr: 'Düzen, yasa ve medeniyetin tanrısına bağlı, müttefiklerini komuta eden kanun rahipleri.', features: [{ level: 1, name: "Voice of Authority", desc_tr: 'Bir müttefike 1. seviye veya daha yüksek bir büyü attığında, o müttefik Reaction harcayarak hemen bir silah saldırısı yapabilir.' }] },
            { name: 'Peace Domain', description_tr: 'Barış, uyum ve anlayışın kutsal yolu. Müttefikler arasında güçlü bağlar kuran destek rahipler.', features: [{ level: 1, name: 'Emboldening Bond', desc_tr: 'Bağ kurduğun dostların birbirine yakınken saldırı, yetenek ve Saving Throw atışlarına [1d4] ekleyebilirler.' }] },
            { name: 'Twilight Domain', description_tr: 'Gün batımı, karanlık öncesi ve uykunun ilahisine tapan, geceyi koruyan rahipler.', features: [{ level: 1, name: 'Eyes of Night', desc_tr: '300ft Darkvision kazanırsın ve bunu başkalarıyla paylaşabilirsin.' }, { level: 1, name: 'Vigilant Blessing', desc_tr: 'Bir canlının sonraki Initiative zarını Advantage ile atmasını sağlarsın.' }] },
        ]
    }
};
