// PART 3: Ranger, Rogue, Sorcerer, Warlock, Wizard
module.exports = {
    'Ranger': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Hunter', description_tr: 'Sürülere, devlere veya hızlı hedeflere karşı en ölümcül avcılık tekniklerini kullanan klasik korucular.', features: [{ level: 3, name: "Hunter's Prey", desc_tr: 'Colossus Slayer (yaralıya +[1d8]), Horde Breaker (ek saldırı) veya Giant Killer (tepki saldırısı) seçeneklerinden birini alırsın.' }] },
            { name: 'Beast Master', description_tr: 'Vahşi bir hayvan dostla birlikte avlanan, hayvanını büyük güce ulaştıran orman koruyucuları.', features: [{ level: 3, name: "Ranger's Companion", desc_tr: 'Seninle birlikte savaşan sadık bir Beast kazanırsın. Hayvanın HP\'si ve AC\'si seninle birlikte güçlenir.' }, { level: 7, name: 'Exceptional Training', desc_tr: 'Hayvan dostun Bonus Action ile hareket eder veya Dash, Disengage, Help aksiyonlarını alabilir.' }] },
            { name: 'Gloom Stalker', description_tr: 'Yeraltı ve karanlıklarda faaliyet gösteren, görünmez kılıklı, ilk turda patlama gücüne sahip gölge avcıları.', features: [{ level: 3, name: 'Dread Ambusher', desc_tr: 'Combat\'ın ilk turunda fazladan 10ft hareket hızı ve [1d8] bonus hasarlı ek bir saldırı yaparsın.' }, { level: 3, name: 'Umbral Sight', desc_tr: 'Darkvision kazanır; karanlıkta (Darkness) seni sadece Darkvision ile görenlere karşı Invisible sayılırsın.' }] },
            { name: 'Horizon Walker', description_tr: 'Farklı boyutlar ve düzlemler arasında kapı açan, kötülerin planar seferlerini durduran sınır korucuları.', features: [{ level: 3, name: 'Detect Portal', desc_tr: '1 mil içindeki boyutsal kapıları hissedersin.' }, { level: 3, name: 'Planar Warrior', desc_tr: 'Bonus Action ile bir sonraki saldırını Force hasarına dönüştürüp fazladan [1d8] hasar eklersin.' }] },
            { name: 'Monster Slayer', description_tr: 'Özellikle güçlü büyülü canavarları ve iblisleri hedefleyen, onları zayıflatmayı uzmanlaştıran avcılar.', features: [{ level: 3, name: "Hunter's Sense", desc_tr: 'Bir yaratığın (Creature) bağışıklıklarını (Immunities) ve dirençlerini (Resistances) hissedebilirsin.' }, { level: 3, name: 'Slayer\'s Prey', desc_tr: 'Bir hedefe hasar ekleyen özel bir işaret yaparsın; o hedefe yaptığın ilk saldırı fazladan [1d6] hasar verir.' }] },
            { name: 'Fey Wanderer', description_tr: 'Feywild\'ın büyüsünü içinde taşıyan, büyüleyici aura ve kılık değiştirme yetenekleriyle savaşan doğa gezginleri.', features: [{ level: 3, name: 'Dreadful Strikes', desc_tr: 'Turda bir kez silah saldırına [1d4] (seviye ile artar) Psychic hasarı eklersin.' }, { level: 3, name: 'Otherworldly Glamour', desc_tr: 'Charm/Frighten etkilerine karşı Advantage kazanırsın; Charisma Skill kontrollerine Wisdom modifier eklersin.' }] },
            { name: 'Swarmkeeper', description_tr: 'Etrafında sürekli hareket eden küçük varlıklar (böcek, yaprak, parıltı) bulutu taşıyan ve bunu silah olarak kullanan doğa bağlantılı korucular.', features: [{ level: 3, name: 'Gathered Swarm', desc_tr: 'Saldırı sonrası sürün düşmanı 15ft iter, sana 5ft uçuş (Fly) verir veya saldırıya [1d6] (seviye ile artar) hasar ekler.' }] },
        ]
    },
    'Rogue': {
        subclass_unlock_level: 3,
        subclasses: [
            { name: 'Thief', description_tr: 'Hırsızlık, akrobasi ve hız konusunda mükemmelleşmiş klasik soyguncular.', features: [{ level: 3, name: 'Fast Hands', desc_tr: 'Bonus Action ile kilit açabilir (Sleight of Hand), tuzak bozabilir veya eşya kullanabilirsin (Use an Object).' }, { level: 3, name: 'Second-Story Work', desc_tr: 'Tırmanma hızın hareket hızına eşit olur; zıplama mesafen Dexterity kadar artar.' }] },
            { name: 'Assassin', description_tr: 'Sürprizi avantaja çeviren, ilk turda yıkıcı hasar veren suikastçılar.', features: [{ level: 3, name: 'Bonus Proficiencies', desc_tr: 'Disguise Kit ve Poisoner\'s Kit için Proficiency kazanırsın.' }, { level: 3, name: 'Assassinate', desc_tr: 'Senden sonra Initiative alan rakiplere Advantage ile saldırırsın. Surprise edilen rakiplere yapılan vuruş otomatik Critical Hit olur.' }] },
            { name: 'Arcane Trickster', description_tr: 'Yanılsamalar ve büyülerle aldatmayı harmanlayan, Sneak Attack\'ı sihirle güçlendiren büyücü hırsızlar.', features: [{ level: 3, name: 'Spellcasting', desc_tr: 'Enchantment ve Illusion ağırlıklı Wizard büyüleri öğrenirsin.' }, { level: 3, name: 'Mage Hand Legerdemain', desc_tr: 'Görünmez Mage Hand ile kilit açabilir ve eşya çalabilirsin. Mage Hand\'i Bonus Action ile kontrol edebilirsin.' }] },
            { name: 'Inquisitive', description_tr: 'Her ayrıntıyı fark eden, yalanı sezebilen ve tek saldırıda düşmanı istismar eden dedektif savaşçılar.', features: [{ level: 3, name: 'Ear for Deceit', desc_tr: 'Insight zarlarında 7 veya altı attığında zar sonucunu 8 sayarsın.' }, { level: 3, name: 'Eye for Detail', desc_tr: 'Bonus Action ile Perception veya Investigation zarı atabilirsin.' }, { level: 3, name: 'Insightful Fighting', desc_tr: 'Bonus Action ile rakibini analiz edip ona karşı 1 dakika boyunca Sneak Attack yapabilirsin (müttefik gerekmez).' }] },
            { name: 'Mastermind', description_tr: 'Sosyal manipülasyonu silah olarak kullanan, müttefiklerine taktiksel avantaj kazandıran strateji uzmanları.', features: [{ level: 3, name: 'Master of Intrigue', desc_tr: 'İki dil, Disguise Kit, Forgery Kit ve bir Gaming Set için Proficiency kazanırsın.' }, { level: 3, name: 'Master of Tactics', desc_tr: 'Help aksiyonunu 30ft menzil ile Bonus Action olarak kullanabilirsin.' }] },
            { name: 'Scout', description_tr: 'Ön keşif ve doğada hayatta kalmayı mükemmelleştirmiş, ilk turda yıldırım hızıyla hareket eden izci hırsızlar.', features: [{ level: 3, name: 'Skirmisher', desc_tr: 'Bir düşman yanına geldiğinde Reaction ile 15ft kaçabilirsin (Opportunity Attack tetiklemez).' }, { level: 3, name: 'Survivalist', desc_tr: 'Nature ve Survival Skills için Proficiency (ve Expertise) kazanırsın.' }] },
            { name: 'Swashbuckler', description_tr: 'Düelloda rakibini dans ettiren, tek başına çalışmayı seven teatral kılıç ustaları.', features: [{ level: 3, name: 'Fancy Footwork', desc_tr: 'Yakın dövüşte saldırdığın bir düşman o tur sana Opportunity Attack yapamaz.' }, { level: 3, name: 'Rakish Audacity', desc_tr: 'Yanında dostun olmasa da 5ft içindeyse Sneak Attack vurabilirsin. Initiative zarlarına [CHA] eklersin.' }] },
            { name: 'Phantom', description_tr: 'Ölümle yakın bağı kullanan, hayaletlerin güçlerine dokunan ve düşmanların canından güç devşiren ölüm hırsızları.', features: [{ level: 3, name: 'Whispers of the Dead', desc_tr: 'Her Long Rest sonrası rastgele bir Skill veya Tool Proficiency kazanırsın.' }, { level: 3, name: 'Wails from the Grave', desc_tr: 'Sneak Attack vurduğunda 30ft içindeki başka bir hedefe [Sneak Attack Zarının Yarısı] kadar Necrotic hasar verirsin.' }] },
            { name: 'Soulknife', description_tr: 'Psiyonik enerjiyle oluşturduğu zihinsel bıçaklarla savaşan ve zihin kontrolü yapabilen psi hırsızlar.', features: [{ level: 3, name: 'Psionic Power', desc_tr: 'Seviyene göre artan Psionic Energy Dice havuzu kazanırsın; bunları ıskaladığın zarları artırmak veya telepatik bağ kurmak için kullanırsın.' }, { level: 3, name: 'Psychic Blades', desc_tr: 'Zihninden [1d6] (Main) ve [1d4] (Bonus) hasar veren psiyonik bıçaklar çıkarırsın.' }] },
        ]
    },
    'Sorcerer': {
        subclass_unlock_level: 1,
        subclasses: [
            { name: 'Draconic Bloodline', description_tr: 'Soyunda ejderha kanı taşıyan, doğuştan element büyüsü yeteneği ve ejderha direncine sahip sihirbazlar.', features: [{ level: 1, name: 'Dragon Ancestor', desc_tr: 'Bir ejderha tipi seç (ateş, buz vb.); o elementin hasarına direnç kazanırsın.' }, { level: 1, name: 'Draconic Resilience', desc_tr: 'AC\'n zırhsızken 13 + DEX olur; ayrıca her seviyede +1 HP kazanırsın.' }] },
            { name: 'Wild Magic', description_tr: 'Saf kaotik büyü enerjisi barındıran, kontrol edilemez sihir patlamaları yaşayan tahmin edilemez büyücüler.', features: [{ level: 1, name: 'Wild Magic Surge', desc_tr: '1. seviye veya üstü büyü attığında DM d20 attırabilir; 1 gelirse Wild Magic Surge tablosundan rastgele bir etki oluşur.' }, { level: 1, name: 'Tides of Chaos', desc_tr: 'Bir saldırı, yetenek testi veya kurtarma atışına Advantage kazanırsın; kullandıktan sonra Wild Magic tetikleme şansın artar.' }] },
            { name: 'Divine Soul', description_tr: 'Soyunda ilahi bir dokunuş barındıran, hem sihirbaz hem de rahip listesinden büyü kullanan kutsal büyücüler.', features: [{ level: 1, name: 'Divine Magic', desc_tr: 'Cleric büyü listesine erişim kazanırsın.' }, { level: 1, name: 'Favored by the Gods', desc_tr: 'Günde 1 kez başarısız bir saldırı veya kurtarma atışına [2d4] ekleyerek sonucu değiştirebilirsin.' }] },
            { name: 'Shadow Magic', description_tr: 'Shadowfell\'in karanlığından güç devşiren, karanlıkta görünmez olan ve gölge köpekleri çağıran sihirbazlar.', features: [{ level: 1, name: 'Eyes of the Dark', desc_tr: '120ft Darkvision kazanırsın. Darkness büyüsünü Sorcery Point ile attığında içini görebilirsin.' }, { level: 1, name: 'Strength of the Grave', desc_tr: 'HP\'n 0\'a düşünce Charisma Saving Throw ile 1 HP\'de ayakta kalabilirsin.' }] },
            { name: 'Storm Sorcery', description_tr: 'Fırtına ve yıldırımın kudretini soyundan getiren, tüm havanın efendisi olan elektrikli sihirbazlar.', features: [{ level: 1, name: 'Wind Speaker', desc_tr: 'Primordial dilini öğrenirsin.' }, { level: 1, name: 'Tempestuous Magic', desc_tr: 'Büyü attıktan sonra Bonus Action ile 10ft uçabilirsin (Opportunity Attack tetiklemez).' }] },
            { name: 'Aberrant Mind', description_tr: 'Uzay ötesi varlıklarla zihinsel temas kuran, psişik güçlere sahip sihirbazlar.', features: [{ level: 1, name: 'Telepathic Speech', desc_tr: '30ft içindeki bir canlıyla telepatik bağ kurabilirsin.' }, { level: 1, name: 'Psionic Spells', desc_tr: 'Psionic Spells listesindeki büyüleri Sorcery Point harcayarak (vokal/somatik bileşen olmadan) atabilirsin.' }] },
            { name: 'Clockwork Soul', description_tr: 'Evrenin düzenini ve yasasını temsil eden sihirbazlar; kaos ve şansı düzeltirler.', features: [{ level: 1, name: 'Restore Balance', desc_tr: 'Reaksiyon ile 60ft içindeki bir canlının Advantage veya Disadvantage etkisini iptal edebilirsin.' }, { level: 1, name: 'Clockwork Spells', desc_tr: 'Düzen ve koruma odaklı ek büyülere erişim kazanırsın.' }] },
            { name: 'Lunar Sorcery', description_tr: 'Ayın büyüsel döngüsünden güç kazanan ve her aşamada farklı yetenekler geliştiren sihirbazlar.', features: [{ level: 1, name: 'Moon Fire', desc_tr: 'Sacred Flame cantrip\'ini öğrenirsin; dolunay evresinde 2 hedefe birden vurabilirsin.' }, { level: 1, name: 'Lunar Embodiment', desc_tr: 'Ay evresine (Full, New, Crescent) göre farklı bonus büyüler ve pasif yetenekler kazanırsın.' }] },
        ]
    },
    'Warlock': {
        subclass_unlock_level: 1,
        subclasses: [
            { name: 'The Archfey', description_tr: 'Feywild\'ın güçlü bir peri varlığıyla anlaşan, büyüleyici cazibe ve illüzyon güçleri taşıyan büyücüler.', features: [{ level: 1, name: 'Fey Presence', desc_tr: 'Bonus Action ile 10ft içindeki düşmanları büyüleyebilir (Charmed) veya korkutabilirsin (Frightened).' }] },
            { name: 'The Fiend', description_tr: 'Cehennemden bir şeytanla anlaşan, ateş ve patlama büyüleri kullanan karanlık güç sihirbazları.', features: [{ level: 1, name: "Dark One's Blessing", desc_tr: 'Bir düşmanı 0 HP\'ye indirdiğinde [CHA + Warlock Lvl] kadar Temporary HP kazanırsın.' }] },
            { name: 'The Great Old One', description_tr: 'Uzay ötesi, anlaşılmaz varlıklarla pakt yapan psişik güçlere sahip, zihni okuyan ve okunan büyücüler.', features: [{ level: 1, name: 'Awakened Mind', desc_tr: '30ft içindeki bir canlıyla telepatik olarak konuşabilirsin; o canlının senin dilini bilmesi gerekmez.' }] },
            { name: 'The Celestial', description_tr: 'Cennet ile bağlantılı bir varlıkla anlaşan, hem hasar hem iyileştirme yapan ışıklı pakt sihirbazları.', features: [{ level: 1, name: 'Healing Light', desc_tr: 'Bonus Action ile bir müttefiği havuzundaki [d6] zarlarıyla iyileştirirsin. Havuzun [1 + Warlock Lvl] kadar d6 içerir.' }] },
            { name: 'The Hexblade', description_tr: 'Gölge alanından kaynaklanan güçlü büyülü bir silahla anlaşan, yakın dövüşte de son derece etkili sihirbazlar.', features: [{ level: 1, name: 'Hexblade\'s Curse', desc_tr: 'Bonus Action: Lanetlediğin hedefe hasar bonusu, 19-20 kritik aralığı ve vurduğunda can kazanma sağlar.' }, { level: 1, name: 'Hex Warrior', desc_tr: 'Martial silah uzmanlığı kazanırsın ve seçilen bir silahta saldırılarını Charisma ile yaparsın.' }] },
            { name: 'The Fathomless', description_tr: 'Okyanusun derinliklerindeki bilinmez bir varlıkla pakt yapan su ve soğuk büyülerin efendisi derin deniz büyücüleri.', features: [{ level: 1, name: 'Tentacle of the Deeps', desc_tr: 'Bonus Action ile bir tentakel çağırırsın; [1d8] Cold hasarı verir ve hızı 10ft azaltır.' }, { level: 1, name: 'Gift of the Sea', desc_tr: 'Yüzme hızı ve su altında nefes alma kazanırsın.' }] },
            { name: 'The Undying', description_tr: 'Ölümü yenmiş ölümsüz bir varlıkla anlaşan ve neredeyse ölümsüzleşen karanlık sihirbazlar.', features: [{ level: 1, name: 'Among the Dead', desc_tr: 'Spare the Dying cantrip\'ini öğrenirsin. Ölümsüzler (Undead) sana saldırmak için Wisdom Saving Throw yapmalıdır.' }] },
            { name: 'The Genie', description_tr: 'Güçlü bir cin patronuyla anlaşan, cin türüne göre element güçleri kazanan sihirbazlar.', features: [{ level: 1, name: "Genie's Vessel", desc_tr: 'Bir lamba veya yüzüğe (vessel) sahip olursun; içine girebilir ve vuruşlarına element hasarı ekleyebilirsin.' }, { level: 1, name: 'Bottled Respite', desc_tr: 'Vessel\'in içine girerek güvenli bir mola yapabilirsin.' }] },
            { name: 'The Undead', description_tr: 'Lich veya güçlü bir vampir gibi ölümsüz bir varlıkla pakt yapan, ölümün sırrına erişmiş karanlık büyücüler.', features: [{ level: 1, name: 'Form of Dread', desc_tr: 'Bonus Action ile korkutucu bir form alarak Temporary HP kazanırsın ve vurduğun düşmanları korkutabilirsin (Frightened).' }] },
        ]
    },
    'Wizard': {
        subclass_unlock_level: 2,
        subclasses: [
            { name: 'School of Abjuration', description_tr: 'Savunma, kovma ve nötralize etme büyülerinde uzmanlaşmış koruma büyücüleri.', features: [{ level: 2, name: 'Abjuration Savant', desc_tr: 'Abjuration büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Arcane Ward', desc_tr: 'Bir Abjuration büyüsü attığında [2 * Wizard Lvl + INT] kadar hasar emen bir kalkan oluşturursun.' }] },
            { name: 'School of Conjuration', description_tr: 'Varlıkları ve nesneleri çağırma veya teleport büyülerinde uzmanlaşmış çağırma büyücüleri.', features: [{ level: 2, name: 'Conjuration Savant', desc_tr: 'Conjuration büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Minor Conjuration', desc_tr: 'Action: 10 kübik feet\'ten büyük olmayan (anahtar, kadeh vb.) cansız bir nesne yaratırsın; hasar alınca kaybolur.' }] },
            { name: 'School of Divination', description_tr: 'Geleceği gören, gizlileri keşfeden ve zarları manipüle eden kehanet büyücüleri.', features: [{ level: 2, name: 'Divination Savant', desc_tr: 'Divination büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Portent', desc_tr: 'Her Long Rest sonrası 2 adet d20 atarsın; bu zarları o gün içinde herhangi bir zarın yerine (lehinize veya aleyhinize) kullanabilirsin.' }] },
            { name: 'School of Enchantment', description_tr: 'Zihinleri kontrol ederek düşmanları büyüleyen veya dostlarını güçlendiren büyüleme ustaları.', features: [{ level: 2, name: 'Enchantment Savant', desc_tr: 'Enchantment büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Hypnotic Gaze', desc_tr: 'Action: 5ft içindeki bir canlıyı büyüleyerek (Charmed) hareket edemez ve konuşamaz hale getirirsin.' }] },
            { name: 'School of Evocation', description_tr: 'Alan vurucu element büyülerini mükemmelleştiren, dostlarını hasardan koruyabilen yıkım büyücüleri.', features: [{ level: 2, name: 'Evocation Savant', desc_tr: 'Evocation büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Sculpt Spells', desc_tr: 'Alan büyüleri atarken içindeki [1 + Büyü Sv.] kadar müttefiki koruyarak hasar almamalarını sağlarsın.' }] },
            { name: 'School of Illusion', description_tr: 'Yanılsamaları gerçekmiş gibi kullanan, savaş alanını görsel karmaşaya boğan yanılsama büyücüleri.', features: [{ level: 2, name: 'Illusion Savant', desc_tr: 'Illusion büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Improved Minor Illusion', desc_tr: 'Minor Illusion cantrip\'ini aynı anda hem ses hem görüntü oluşturacak şekilde geliştirirsin.' }] },
            { name: 'School of Necromancy', description_tr: 'Ölüleri yönlendiren ve hayat enerjisini toplayan karanlık nekromantlar.', features: [{ level: 2, name: 'Necromancy Savant', desc_tr: 'Necromancy büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Grim Harvest', desc_tr: 'Büyünle bir canlıyı öldürdüğünde [2 * Sv.] (Nekromansi ise 3 katı) kadar can kazanırsın.' }] },
            { name: 'School of Transmutation', description_tr: 'Maddeyi ve canlıları dönüştüren, kurşunu altına çeviren ve bazen iyileştiren simyacı büyücüler.', features: [{ level: 2, name: 'Transmutation Savant', desc_tr: 'Transmutation büyüsü kopyalama masrafın ve süren yarıya düşer.' }, { level: 2, name: 'Minor Alchemy', desc_tr: 'Bir nesnenin maddesini geçici olarak (ahşap, taş, demir, gümüş vb.) birbirine dönüştürebilirsin.' }] },
            { name: 'Bladesinging', description_tr: 'Kılıç ve büyüyü zarif bir dans içinde birleştiren, AC ve konsantrasyonu büyü kanalıyla artıran uzman büyücüler.', features: [{ level: 2, name: 'Training in War and Song', desc_tr: 'Light Armor, bir tekli Martial Weapon ve Performance Skill için Proficiency kazanırsın.' }, { level: 2, name: 'Bladesong', desc_tr: 'Bonus Action: AC, hareket hızı ve Concentration zarlarına [INT] bonusu kazanırsın.' }] },
            { name: 'War Magic', description_tr: 'Savunma ve saldırıyı eş zamanlı yürüten, büyü-zırh uyumunda mükemmelleşmiş savaş büyücüleri.', features: [{ level: 2, name: 'Arcane Deflection', desc_tr: 'Reaksiyon: AC\'ne +2 veya Saving Throw\'una +4 bonus alırsın.' }, { level: 2, name: 'Tactical Wit', desc_tr: 'Initiative zarlarına [INT] eklersin.' }] },
            { name: 'Order of Scribes', description_tr: 'Büyü kitabını canlı bir varlık olarak uyandıran, büyülerini anlık değiştirebilen akademisyen büyücüler.', features: [{ level: 2, name: 'Awakened Spellbook', desc_tr: 'Büyü kitabın canlanır; büyü türlerini (hasar tipi vb.) anlık değiştirebilir veya kopyalama süresini hızlandırabilirsin.' }, { level: 2, name: 'Manifest Mind', desc_tr: 'Büyü kitabından yayılan zihinsel bir uzantı ile uzaktan büyü atabilirsin.' }] },
            { name: 'Graviturgy Magic', description_tr: 'Yerçekimini manipüle ederek düşmanları iter, çeker veya ağırlaştıran büyücüler.', features: [{ level: 2, name: 'Adjust Density', desc_tr: 'Action: Bir nesneyi veya canlıyı ağırlaştırıp yavaşlatırsın ya da hafifleştirip yükseltirsin.' }] },
            { name: 'Chronurgy Magic', description_tr: 'Zamanın akışını manipüle eden, zarları geri alan ve hasımları zamana sabitleyen büyücüler.', features: [{ level: 2, name: 'Chronal Shift', desc_tr: 'Reaksiyon: Bir saldırı, yetenek veya kurtarma zarını yeniden attırabilirsin (ister lehine ister aleyhinize).' }, { level: 2, name: 'Temporal Awareness', desc_tr: 'Initiative zarlarına [INT] eklersin.' }] }
        ]
    }
};
