// D&D 5e — Tüm Resmi Featler (Tam Liste)
export interface Feat {
    name: string;
    category: 'General' | 'Fighting Style' | 'Epic Boon' | 'Origin' | 'Skill' | 'Half Feat';
    prereq?: string;
    desc_tr: string;
}

export const ALL_FEATS: Feat[] = [
    // ── ORIGIN FEATS ──────────────────────────────────────────────────────────
    { name: 'Alert', category: 'Origin', desc_tr: 'İnisiyatif zarlarına +5 bonus. Bilincin açıkken şaşıratamazsın (surprised). Seni göremeyenler sana karşı saldırıda avantaj kazanamaz.' },
    { name: 'Crafter', category: 'Origin', desc_tr: 'Bir zanaatkar aleti ustalığı kazan. Alışveriş yaparken item\'lerde %20 indirim. Uzun dinlenmede ücretsiz küçük eşya üretebilirsin.' },
    { name: 'Healer', category: 'Origin', desc_tr: 'Healer\'s Kit ile Stabilize etme eylemine ekstra 1d6 + proficiency bonus HP eklersin. Ayrıca bir yaratığı sadece 1d6+4 HP ile ayağa kaldırabilirsin.' },
    { name: 'Lucky', category: 'Origin', desc_tr: '3 adet Şans Puanı. Saldırı, yetenek veya kurtarma zarı atacağında ekstra d20 at ve hangisini kullanacağına karar ver. Uzun dinlenmede yenilenir.' },
    { name: 'Magic Initiate (Cleric)', category: 'Origin', desc_tr: 'Cleric listesinden 2 cantrip ve 1 adet 1. seviye büyü öğren. Bu 1. seviye büyüyü günde bir kez, slot harcamadan kullanabilirsin. (Kılıç ve Kalkan — WIS)' },
    { name: 'Magic Initiate (Druid)', category: 'Origin', desc_tr: 'Druid listesinden 2 cantrip ve 1 adet 1. seviye büyü öğren. Slot harcamadan günde bir kez kullanılabilir. (Doğa ve Hayvanlar — WIS)' },
    { name: 'Magic Initiate (Wizard)', category: 'Origin', desc_tr: 'Wizard listesinden 2 cantrip ve 1 adet 1. seviye büyü öğren. Slot harcamadan günde bir kez kullanılabilir. (Gizem ve Bilgi — INT)' },
    { name: 'Musician', category: 'Origin', desc_tr: 'Bir müzik aleti ustalığı kazan. Kısa ya da uzun dinlenmede yarım saatlik müzikle dinlenenlere geçici HP verebilirsin.' },
    { name: 'Savage Attacker', category: 'Origin', desc_tr: 'Yakın dövüş saldırısı yaptığında hasar zarlarını iki kez at ve yüksek sonucu seç. Turda bir kez geçerli.' },
    { name: 'Skilled', category: 'Origin', desc_tr: '3 beceri veya alet ustalığı kazan (proficiency).' },
    { name: 'Tavern Brawler', category: 'Origin', desc_tr: 'Silahsız saldırıların 1d4+STR hasar yapar. İsabetten sonra bonus eylemle Grapple deneyebilirsin. Doğaçlama silahlarla (masa, şişe vb.) da dövüşebilirsin.' },
    { name: 'Tough', category: 'Origin', desc_tr: 'Mevcut ve gelecek seviyeler için maksimum HP\'nin her seviye için 2 artar.' },

    // ── GENERAL FEATS ────────────────────────────────────────────────────────
    { name: 'Ability Score Improvement', category: 'General', desc_tr: 'Bir yetenek skorunu 2 puan artır, ya da iki farklı yetenek skorunu birer puan artır (maksimum 20).' },
    { name: 'Actor', category: 'Half Feat', prereq: 'CHA 13', desc_tr: 'CHA +1. Ses taklidi ve başka bir kişinin kisvesine girme konusunda ustalaşırsın. Deception ve Performance kontrolleri için avantaj kazanırsın.' },
    { name: 'Athlete', category: 'Half Feat', prereq: 'STR veya DEX 13', desc_tr: 'STR veya DEX +1. Tırmanma hızın yarıya düşmez. Yatarken (prone) kalkış sadece 5ft hareket harcar. 5ft koşudan uzun ve yüksek atlama yapabilirsin.' },
    { name: 'Charger', category: 'General', desc_tr: 'Dash eyleminden sonra aynı turda bonus eylemle melee saldırı veya Shove yapabilirsin. Saldırıda +8 veya Shove\'da ekstra 10ft itme kazanırsın.' },
    { name: 'Crossbow Expert', category: 'General', desc_tr: 'Yükleme özelliğini görmezden gelirsin. Yakın mesafede ranged saldırılar dezavantajlı olmaz. Tek el light ranged silahla saldırıdan sonra bonus eylemle hand crossbow ile ekstra saldırı yapabilirsin.' },
    { name: 'Crusher', category: 'General', desc_tr: 'Bludgeoning hasarı vurduğunda özneli 5ft itebilirsin. 20 atarsan düşmanlara üzündeki avantaj verirsin.' },
    { name: 'Defensive Duelist', category: 'General', prereq: 'DEX 13', desc_tr: 'Finesse silah tutarken sana yapılan melee saldırıya karşı reaksiyon olarak proficiency bonusunu AC\'ye ekle — bu saldırı için.' },
    { name: 'Dual Wielder', category: 'General', desc_tr: 'Light olmayan silahlarla da çift ele mücadele yapabilirsin. AC\'ye +1, her iki elde de silah çekip kaldırabilirsin.' },
    { name: 'Dungeon Delver', category: 'General', desc_tr: 'Gizli kapıları ve tuzakları aramakta avantajlı. Tuzak zarlarında avantajlı. Tuzak hasisyatından ek hasar almadan geçme.' },
    { name: 'Durable', category: 'Half Feat', prereq: 'CON 13', desc_tr: 'CON +1. Hit Dice atarken minimum CON modifier kadar atarsın (en az 1). Uzun dinlenmede tam HP\'ye dönersin.' },
    { name: 'Elemental Adept', category: 'General', prereq: 'Büyü yeteneği', desc_tr: 'Bir element türü seç (Asit, soğuk, ateş, yıldırım veya gök gürültüsü). Büyülerin bu elementteki 1\'ler 2 olur. Hasarı bu tipe çevirmede direnç görmezden gel.' },
    { name: 'Fey Touched', category: 'Half Feat', desc_tr: 'INT, WIS veya CHA +1. Misty Step öğren. Divination veya Enchantment\'tan 1. seviye büyü öğren. İkisini günde birer kez slot harcamadan kullanırın.' },
    { name: 'Fighting Initiate', category: 'General', prereq: 'Silah ustalığı', desc_tr: 'Fighter\'ın Fighting Style listesinden bir stil seç. Uzun dinlenmede değiştirebilirsin.' },
    { name: 'Grappler', category: 'General', prereq: 'STR 13', desc_tr: 'Grapple\'da tuttuğun hedefe avantajlı saldırırsın. Hedefe pin atabilirsin — ikisi de Restrained olur.' },
    { name: 'Great Weapon Master', category: 'General', desc_tr: 'Kritik vurduğunda veya düşmanı 0 HP\'ye düşürdüğünde bonus eylemle bir melee saldırı daha yapabilirsin. Saldırıda -5 alıp hasara +10 ekleyebilirsin.' },
    { name: 'Gunner', category: 'General', desc_tr: 'Ateşli silah ustalığı kazan. Yakın mesafede ateşli silah dezavantajı olmaz. DEX +1.' },
    { name: 'Heavily Armored', category: 'Half Feat', prereq: 'Orta zırh ustalığı', desc_tr: 'Ağır zırh ustalığı kazan. STR +1.' },
    { name: 'Heavy Armor Master', category: 'Half Feat', prereq: 'Ağır zırh ustalığı', desc_tr: 'STR +1. Zırhlıyken slashing/piercing/bludgeoning hasar 3 azalır.' },
    { name: 'Inspiring Leader', category: 'General', prereq: 'CHA 13', desc_tr: '10 dakikalık konuşma sonrası 6 hedefe (seni duyacak) CHA modifier + seviye kadar geçici HP ver. Kısa/uzun dinlenmede yenilenir.' },
    { name: 'Keen Mind', category: 'Half Feat', desc_tr: 'INT +1. Gecikmeden kuzey yönünü bilirsin, gün batımını ve doğuşunu takip edersin. Son 30 gün içinde gördüğün şeyleri mükemmel hatırlarsın.' },
    { name: 'Lightly Armored', category: 'General', desc_tr: 'Hafif zırh ustalığı kazan. STR veya DEX +1.' },
    { name: 'Linguist', category: 'General', desc_tr: '3 dil öğren. Şifreli mesajlar oluşturabilir ve çözebilirsin.' },
    { name: 'Mage Slayer', category: 'General', desc_tr: 'Yakın çevrendeki yaratık büyü attığında reaksiyonla saldırırsın. Büyü konsantrasyonu kontrolleri zorlaşır (Disadv.). Büyü karşısında hayatta kalma zarları avantajlı.' },
    { name: 'Martial Adept', category: 'General', desc_tr: 'Fighter Battle Master listesinden iki manöver öğren. 1 d6 Superiority Die kazan (kısa/uzun dinlenmede yenilenir).' },
    { name: 'Medium Armor Master', category: 'General', prereq: 'Orta zırh ustalığı', desc_tr: 'Orta zırhlıyken Stealth dezavantajı yok. DEX bonusunu orta zırha +3\'e kadar ekleyebilirsin.' },
    { name: 'Metamagic Adept', category: 'General', prereq: 'Büyü veya Warlock yeteneği', desc_tr: 'İki Metamagic özelliği seç. 2 Sorcery Point kazan (uzun dinlenmede yenilenir). Bu noktaları Metamagic seçimlerine harcar.' },
    { name: 'Mobile', category: 'General', desc_tr: 'Hareket hızın 10ft artar. Dash\'ten sonra zorlu arazi bedeli yok. Saldırdığın düşmandan fırsat saldırısı yemezsin (vurup kaçarsın).' },
    { name: 'Moderately Armored', category: 'Half Feat', prereq: 'Hafif zırh ustalığı', desc_tr: 'Orta zırh ve kalkan ustalığı kazan. STR veya DEX +1.' },
    { name: 'Mounted Combatant', category: 'General', desc_tr: 'Bineğinden küçük hedeflere avantajlı saldırı. Bineğini hedef alan saldırıları kendinize yönlendirebilirsin. Bineğin başarılı DEX saves\'te hiç hasar almaz.' },
    { name: 'Observant', category: 'Half Feat', prereq: 'INT veya WIS 13', desc_tr: 'INT veya WIS +1. Dudak okuyabilirsin (dil bilirsen). Pasif Perception ve Investigation +5.' },
    { name: 'Piercer', category: 'General', desc_tr: 'Piercing hasarla vurduğunda hasar zarlarından biri yeniden at. Kritik isabette ekstra bir hasar zarı at.' },
    { name: 'Poisoner', category: 'General', desc_tr: 'Zehirlenmezsin, daha çabuk zehir yaparsın. Silahına 1d6 ekstra poison hasar veren bir zehir uygulayabilirsin.' },
    { name: 'Polearm Master', category: 'General', desc_tr: 'Halberd, glaive, quarterstaff gibi silahlarla hasar zanı d4 olan bonus aksiyon saldırısı yap. Düşman hareket ile 10ft aralığına girerse reaksiyonla saldır.' },
    { name: 'Resilient', category: 'Half Feat', desc_tr: 'Seçilen ability +1. O abilityye ait kurtarma zarlarında ustalık kazanırsın.' },
    { name: 'Ritual Caster', category: 'General', prereq: 'INT veya WIS 13', desc_tr: 'Bir büyücü sınıfından iki Ritual büyüsü içeren bir Ritual Book kazan. Yeni Ritual büyüleri ekleyebilirsin.' },
    { name: 'Sentinel', category: 'General', desc_tr: 'Fırsat saldırıları hedefin hızını 0\'a düşürür. Sana yakın düşmanlara başka birine yaptığı saldırılara karşı reaksiyonla saldırabilirsin. Dodge eylemine rağmen fırsat saldırısı yapabilirsin.' },
    { name: 'Shadow Touched', category: 'Half Feat', desc_tr: 'INT, WIS veya CHA +1. Invisibility öğren. Illusion veya Necromancy\'dan 1. seviye büyü öğren. İkisini günde birer kez slot harcamadan kullanırsın.' },
    { name: 'Sharpshooter', category: 'General', desc_tr: 'Uzun menzil dezavantajı yok. Yarım ve 3/4 siper görmezden gel. Ranged saldırıda -5 alıp hasara +10 ekleyebilirsin.' },
    { name: 'Shield Master', category: 'General', desc_tr: 'Eylemde silahla saldırdıktan sonra bonus eylemle kalkanla Shove yapabilirsin. Dex zarı gerektiren etkilere karşı kalkanı ekstra koruma sağlar. Pasif Dex kurtarma bonusu.' },
    { name: 'Skill Expert', category: 'General', desc_tr: 'Bir yetenek skoru +1. Bir beceri ustalığı kazan. Sahip olduğun ustalıklardan birinde Expertise kazan.' },
    { name: 'Skulker', category: 'General', prereq: 'DEX 13', desc_tr: 'Gizlenmeye çalışırken hafifçe göründüğünde gizlenme iptal olmaz. Ranged saldırı tutmazsa gizlenme korunur.' },
    { name: 'Slasher', category: 'General', desc_tr: 'Slashing hasarla vurduğunda -10ft hareket hızı ver (tur sonu kadar). 20\'ye kritik vurduğunda hedefe saldırı zarlarında disavantaj ver.' },
    { name: 'Spell Sniper', category: 'General', prereq: 'Büyü yeteneği', desc_tr: 'Saldırı atışı gerektiren büyülerin menzili iki katına çıkar. Bu büyüler siper avantajını yoksayar. Bir saldırı büyüsü cantrip öğren.' },
    { name: 'Telekinetic', category: 'Half Feat', desc_tr: 'INT, WIS veya CHA +1. Mage Hand öğren (ya da zenginleştir). Bonus eylemle 5ft içindeki birini 5ft itebilirsin (STR save: 8+Prof+seçilen stat).' },
    { name: 'Telepathic', category: 'Half Feat', desc_tr: 'INT, WIS veya CHA +1. 60ft uzağındaki birine zihinsel mesaj iletebilirsin. Detect Thoughts büyüsünü slot harcamadan günde bir kez kullanabilirsin.' },
    { name: 'War Caster', category: 'General', prereq: 'Büyü yeteneği', desc_tr: 'Konsantrasyon kurtarma zarlarında avantaj. Ellerde silah/kalkanken somatik bileşenle büyü yapabilirsin. Fırsat saldırısı yerine büyü kullanabilirsin.' },
    { name: 'Weapon Master', category: 'Half Feat', desc_tr: 'STR veya DEX +1. 4 silah ustalığı kazan.' },

    // ── SKILL FEATS ──────────────────────────────────────────────────────────
    { name: 'Acrobat', category: 'Skill', prereq: 'Acrobatics ustalığı', desc_tr: 'DEX +1. Acrobatics kontrollerinde Expertise kazan. Bonus eylemle 15ft içinde ayakta duran bir düşmanın yanına atlayabilirsin.' },
    { name: 'Animal Handler', category: 'Skill', prereq: 'Animal Handling ustalığı', desc_tr: 'WIS +1. Animal Handling\'de Expertise. Bonus eylemle evcilleştirilmiş hayvanlara komut verebilirsin.' },
    { name: 'Arcanist', category: 'Skill', prereq: 'Arcana ustalığı', desc_tr: 'INT +1. Arcana\'da Expertise. Detec Magic ve Identify büyülerini slot harcamadan birer kez kullanabilirsin.' },
    { name: 'Brawny', category: 'Skill', prereq: 'Athletics ustalığı', desc_tr: 'STR +1. Athletics\'te Expertise. Carry capacity, push/drag/lift iki katına çıkar.' },
    { name: 'Charlatan', category: 'Skill', prereq: 'Deception ustalığı', desc_tr: 'CHA +1. Deception\'da Expertise. Bir kişiyi saatler boyunca kandırabilirsin; onlar sana karşı Insight yaparsa dezavantaj.' },
    { name: 'Chef', category: 'Skill', desc_tr: 'CON veya WIS +1. Kısa dinlenmede yaptığın yemekten 1d8 ek geçici HP. Uzun dinlenmede parti için geçici HP paketi hazırlayabilirsin.' },
    { name: 'Clothier', category: 'Skill', desc_tr: 'DEX +1. Weaver\'s Tools ustalığı ve Expertise. Yaptığın kıyafetlerle karşılaşma sonuçlarını değiştirebilirsin.' },
    { name: 'Cohort of Chaos', category: 'General', desc_tr: 'Kaotik bir güçle bağlısın. Her tur başında 1\'den 6\'ya kadar rastgele bir tablo etkisi ortaya çıkabilir.' },
    { name: 'Divinely Favored', category: 'Half Feat', desc_tr: 'INT, WIS veya CHA +1. Tanrından bir büyü listesi öğren. Uzun dinlenmede slot harcamadan kullanabilirsin.' },
    { name: 'Expert', category: 'General', desc_tr: 'İki beceri veya araç ustalığında Expertise kazan. Bir beceri ustalığı daha kazan.' },
    { name: 'Fade Away', category: 'Half Feat', prereq: 'Gnome, DEX veya INT 13', desc_tr: 'DEX veya INT +1. Hasar aldığında reaksiyon olarak Invisible ol (tur sonunda ya da saldırana kadar). Uzun dinlenmede yenilenir.' },
    { name: 'Fey Teleportation', category: 'Half Feat', prereq: 'High Elf', desc_tr: 'INT veya CHA +1. Sylvan dilini öğren. Misty Step büyüsünü slot harcamadan günde bir kez kullanabilirsin.' },
    { name: 'Flash Recall', category: 'Half Feat', prereq: 'Büyü sınıfı', desc_tr: 'INT +1. Hazırladığın büyülerden birini anında değiştirirsin. Kısa/uzun dinlenmede yenilenir.' },
    { name: 'Flames of Phlegethos', category: 'Half Feat', prereq: 'Tiefling', desc_tr: 'INT veya CHA +1. Fire büyüsüyle hasar zarı atarken 1\'ler yeniden atılır. 1 turda alevlere bürünürsün; yakın saldırılara fire hasar.' },
    { name: 'Gift of the Chromatic Dragon', category: 'General', desc_tr: 'Bonus eylemle saldırın ek 1d4 hasar (elementel) kazanır. Reaksiyon olarak elementel hasara direnç kazan. Uzun dinlenmede yenilenir.' },
    { name: 'Gift of the Gem Dragon', category: 'Half Feat', desc_tr: 'INT, WIS veya CHA +1. Sana yakın melee saldırı yapana reaksiyon olarak psionik patlamayla it (STR kurtarma).' },
    { name: 'Gift of the Metallic Dragon', category: 'General', desc_tr: 'Cure Wounds büyüsünü slot harcamadan, prof. Bonus kadar kullanabilirsin. Reaksiyon olarak müttefikin AC\'ye prof bonus eklersin (uzun dinlenmede yenilenir).' },
    { name: 'Hardy', category: 'Skill', prereq: 'Survival ustalığı', desc_tr: 'CON +1. Survival\'da Expertise. Kısa dinlenmede Hit Die ile iyileşirken ek CON modifier HP kazan.' },
    { name: 'Herbalism Master', category: 'Skill', prereq: 'Medicine ustalığı', desc_tr: 'WIS +1. Herbalism Kit ustalığı. Potion of Healing üretebilir, zehirleri önleyebilirsin.' },
    { name: 'Historian', category: 'Skill', prereq: 'History ustalığı', desc_tr: 'INT +1. History\'de Expertise. Tarihi bilgiler için avantaj. Belirsiz olayları harikulade hatırlama.' },
    { name: 'Investigator', category: 'Skill', prereq: 'Investigation ustalığı', desc_tr: 'INT +1. Investigation\'da Expertise. Sahneleri incelerken detayları anında fark edersin.' },
    { name: 'Knight of the Crown', category: 'General', desc_tr: 'Savaş sırasında tutarlı ilk sıradayken comrade\'lere avantajlı saldırı hakkı.' },
    { name: 'Lore of the Gods', category: 'Half Feat', prereq: 'Half-Elf', desc_tr: 'CHA +1. İki ilahi listeden cantrip öğren.' },
    { name: 'Medic', category: 'Skill', prereq: 'Medicine ustalığı', desc_tr: 'WIS +1. Medicine\'da Expertise. Kısa dinlenmede diğer yaratıklara ekstra Hit Die ile iyileşme sağlayabilirsin.' },
    { name: 'Menacing', category: 'Skill', prereq: 'Intimidation ustalığı', desc_tr: 'CHA +1. Intimidation\'da Expertise. Başka olarak Frighten durumu uygulayabilirsin.' },
    { name: 'Naturalist', category: 'Skill', prereq: 'Nature ustalığı', desc_tr: 'INT +1. Nature\'da Expertise. Druidcraft ve Speak with Animals öğren.' },
    { name: 'Perceptive', category: 'Skill', prereq: 'Perception ustalığı', desc_tr: 'WIS +1. Perception\'da Expertise. Pasif Perception +1. Gizli ya da saklı şeyleri atlatamazsın.' },
    { name: 'Performer', category: 'Skill', prereq: 'Performance ustalığı', desc_tr: 'CHA +1. Performance\'da Expertise. Müzik veya show ile kalabalıkları etkileyebilirsin.' },
    { name: 'Practiced Expert', category: 'Skill', desc_tr: 'Bir yetenek +1. Bir beceri/araç ustalığı ve Expertise kazan.' },
    { name: 'Quick Fingers', category: 'Skill', prereq: 'Sleight of Hand ustalığı', desc_tr: 'DEX +1. SoH\'da Expertise. Hızlı parmak hareketleriyle eşyaları gizleyebilir, çekebilirsin.' },
    { name: 'Righteous Heritor', category: 'General', desc_tr: 'Kahramanca geçmişin var. Müttefikin 0 HP\'ye düşünce reaksiyonla 1d10+Prof bonus HP ver.' },
    { name: 'Scholar of the Arcane', category: 'General', prereq: 'Arcana ustalığı', desc_tr: 'Arcane araştırmalarında derinleştin. Büyüsel eserler ve büyülü varlıklar hakkında ek bilgi.' },
    { name: 'Skillful', category: 'Skill', desc_tr: 'Bir yetenek +1. İki beceri ustalığı kazan.' },
    { name: 'Squat Nimbleness', category: 'Half Feat', prereq: 'Gnome veya Halfling', desc_tr: 'STR veya DEX +1. Hareket hızı +5ft. Athletics veya Acrobatics\'te Expertise. Grapple escape avantajlı.' },
    { name: 'Stealthy', category: 'Skill', prereq: 'Stealth ustalığı', desc_tr: 'DEX +1. Stealth\'te Expertise. Şehirde ve ormanda takip edilmeden geçmek için özel yetkinlik.' },
    { name: 'Survivalist', category: 'Skill', prereq: 'Survival ustalığı', desc_tr: 'WIS +1. Survival\'da Expertise. Kısa dinlenmeler için özelleşmiş destek iyileşmesi.' },
    { name: 'Theologian', category: 'Skill', prereq: 'Religion ustalığı', desc_tr: 'INT +1. Religion\'da Expertise. Thaumaturgy ve Detect Evil and Good öğren.' },
    { name: 'Wood Elf Magic', category: 'General', prereq: 'Wood Elf', desc_tr: 'Longstrider ve Pass Without Trace büyülerini öğren; slot harcamadan günde birer kez kullanabilirsin.' },

    // ── EPIC BOON FEATS (Seçkin Feats) ─────────────────────────────────────
    { name: 'Boon of Combat Prowess', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'STR, DEX veya CON +1 (maksimum 30). Turda bir kez kaçırdığın melee saldırıyı isabet ettir.' },
    { name: 'Boon of Dimensional Travel', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'INT, WIS veya CHA +1 (maksimum 30). Bonus eylemle 30ft Misty Step gibi ışınlanabilirsin.' },
    { name: 'Boon of Energy Resistance', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'CON +1. İki hasar tipine direnç kazan; uzun dinlenmede değiştirebilirsin.' },
    { name: 'Boon of Fate', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'WIS +1. Yakınında biri zar attığında d10 ekleyebilir veya çıkartabilirsin. Uzun dinlenmede Prof.Bonus kadar kullanım.' },
    { name: 'Boon of Fortitude', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'CON +1 (maks.30). Maksimum HP Prof.Bonus x 4 kadar artar. Yarı ölü regene yeteneği.' },
    { name: 'Boon of Irresistible Offense', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'STR veya DEX +1 (maks.30). Saldırıların magical sayılır, bludgeoning/slashing/piercing hasarda seç.' },
    { name: 'Boon of Recovery', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'CON +1 (maks.30). Günde bir kez 0 HP\'de düşmeden 1 HP ile kalabilirsin. Birkaç Hit Die er az bir kez kullanabilirsin.' },
    { name: 'Boon of Skill', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'INT +1. Tüm becerilerde ustalık kazan. Bir becerinde Expertise.' },
    { name: 'Boon of Speed', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'DEX +1 (maks.30). Hareket hızı +30ft. Bonus eylemle Disengage veya Dash.' },
    { name: 'Boon of Spell Recall', category: 'Epic Boon', prereq: 'Sv.19, Büyü yeteneği', desc_tr: 'INT +1. Günde bir kez harcadığın bir slot geri kazan.' },
    { name: 'Boon of the Night Spirit', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'DEX veya CHA +1 (maks.30). Çok az ışıkta veya karanlıkta half-invisible olursun, Stealth avantajlı.' },
    { name: 'Boon of Truesight', category: 'Epic Boon', prereq: 'Sv.19', desc_tr: 'WIS +1 (maks.30). 60ft aralığında True Sight — gizli katmanları, illusion\'ları, görünmezleri, gerçek formları görürsün.' },

    // ── FIGHTING STYLE FEATS ─────────────────────────────────────────────────
    { name: 'FS: Archery', category: 'Fighting Style', desc_tr: 'Menzilli silah saldırı zarlarına +2 bonus.' },
    { name: 'FS: Blind Fighting', category: 'Fighting Style', desc_tr: '10ft Blindsight — görünmez veya gizlenmiş yaratıklar bile net görülür.' },
    { name: 'FS: Defense', category: 'Fighting Style', desc_tr: 'Zırh giyerken AC\'ye +1.' },
    { name: 'FS: Dueling', category: 'Fighting Style', desc_tr: 'Tek elde silah ve diğer elde silah yokken +2 hasar.' },
    { name: 'FS: Great Weapon Fighting', category: 'Fighting Style', desc_tr: 'İki elli silahlarla 1 ve 2 gelen hasar zarlarını yeniden atabilirsin.' },
    { name: 'FS: Interception', category: 'Fighting Style', desc_tr: 'Yanındaki bir yaratığa yapılan hasarı reaksiyon olarak 1d10+Prof azaltabilirsin.' },
    { name: 'FS: Protection', category: 'Fighting Style', prereq: 'Kalkan', desc_tr: 'Yakınındaki birine yapılan saldırıya karşı reaksiyon olarak o saldırıya dezavantaj ver.' },
    { name: 'FS: Superior Technique', category: 'Fighting Style', desc_tr: 'Battle Master listesinden 1 manöver öğren. 1d6 Superiority Die kazan.' },
    { name: 'FS: Thrown Weapon Fighting', category: 'Fighting Style', desc_tr: 'Fırlatılan silahlarla +2 hasar. Silahı saldırının parçası olarak bonus eylem olmadan çekebilirsin.' },
    { name: 'FS: Two-Weapon Fighting', category: 'Fighting Style', desc_tr: 'Çift elde saldırılarda hasar zarına ability modifier ekle.' },
    { name: 'FS: Unarmed Fighting', category: 'Fighting Style', desc_tr: 'Silahsız saldırılar 1d6 (ya da 1d8 boş el varsa) hasar verir. Grappled düşmanlar her tur 1d4 hasar alır.' },
];

// ── METAMAGIC SEÇENEKLERİ (Metamagic Adept veya Sorcerer için) ───────────────
// ── METAMAGIC SEÇENEKLERİ (Metamagic Adept veya Sorcerer için) ───────────────
export const ALL_METAMAGICS = [
    { name: "Careful Spell", desc: "1 sorcery point harcayarak büyünün kurtarma zarından bazı müttefikleri korursun." },
    { name: "Distant Spell", desc: "1 sorcery point harcayarak büyünün menzilini iki katına çıkar ya da touch büyüleri 30ft menzilli yap." },
    { name: "Empowered Spell", desc: "1 sorcery point harcayarak hasar zarlarından CHA mod. kadar zarı yeniden at." },
    { name: "Extended Spell", desc: "1 sorcery point harcayarak büyünün süresini iki katına çıkar (maksimum 24 saat)." },
    { name: "Heightened Spell", desc: "3 sorcery point harcayarak bir hedefe büyünün ilk kurtarma zarında dezavantaj ver." },
    { name: "Quickened Spell", desc: "2 sorcery point harcayarak döküm süresi 1 action olan büyüyü 1 bonus action olarak yap." },
    { name: "Subtle Spell", desc: "1 sorcery point harcayarak büyüyü somatik ve sözlü bileşenleri olmadan yap." },
    { name: "Twinned Spell", desc: "Büyü seviyesi kadar (cantrip için 1) point harcayarak tek hedefli büyüyü ikinci bir hedefe de ulaştır." },
    { name: "Seeking Spell", desc: "2 sorcery point harcayarak kaçıran bir büyü saldırı zarını yeniden at." },
    { name: "Transmuted Spell", desc: "1 sorcery point harcayarak elementel hasar tipini başka bir element tipine değiştir." }
];

// ── BATTLE MASTER MANEUVERS (Martial Adept veya Fighter için) ────────────────
export const ALL_MANEUVERS = [
    { name: "Ambush", desc: "İnisiyatif veya Stealth zarına Superiority Die ekle." },
    { name: "Bait and Switch", desc: "Müttefikle yer değiştir ve AC bonusu kazan." },
    { name: "Brace", desc: "Yaratık menziline girdiğinde reaksiyonla saldır." },
    { name: "Commander's Strike", desc: "Saldırından feragat edip müttefike saldırı yaptır." },
    { name: "Commanding Presence", desc: "Intimidation, Performance veya Persuasion zarına ekle." },
    { name: "Disarming Attack", desc: "Hedefi elindeki eşyayı düşürmeye zorla." },
    { name: "Distracting Strike", desc: "Hedefe yapılan bir sonraki saldırıya avantaj sağla." },
    { name: "Evasive Footwork", desc: "Hareket ederken AC'ye Superiority Die ekle." },
    { name: "Feinting Attack", desc: "Bonus eylemle bir sonraki saldırına avantaj ve ek hasar kazan." },
    { name: "Goading Attack", desc: "Hedefi sana saldırmaya zorla (başkasına disadv)." },
    { name: "Grappling Strike", desc: "Saldırı sonrası bonus eylemle Grapple dene." },
    { name: "Lunging Attack", desc: "Melee saldırı menzilini 5ft artır." },
    { name: "Maneuvering Attack", desc: "Müttefikin güvenle hareket etmesini sağla." },
    { name: "Menacing Attack", desc: "Hedefi Frightened durumuna sokmaya çalış." },
    { name: "Parry", desc: "Hasarı reaksiyonla azalt." },
    { name: "Precision Attack", desc: "Saldırı zarına Superiority Die ekle." },
    { name: "Pushing Attack", desc: "Hedefi 15ft uzağa itmeye çalış." },
    { name: "Quick Toss", desc: "Bonus eylemle fırlatılan silah saldırısı yap." },
    { name: "Rally", desc: "Müttefike geçici HP ver." },
    { name: "Riposte", desc: "Sana ıskalayan düşmana reaksiyonla saldır." },
    { name: "Sweeping Attack", desc: "Saldırı hasarını yanındaki başka birine de yay." },
    { name: "Tactical Assessment", desc: "History, Insight veya Investigation zarına ekle." },
    { name: "Trip Attack", desc: "Hedefi yere düşürmeye (prone) çalış." }
];

// ── FIGHTING STYLES (Fighting Initiate veya Fighter için) ────────────────────
export const ALL_FIGHTING_STYLES = [
    { name: "Archery", desc: "Menzilli silah saldırılarına +2 bonus." },
    { name: "Blind Fighting", desc: "10ft Blindsight kazan." },
    { name: "Defense", desc: "Zırhlıyken AC'ye +1." },
    { name: "Dueling", desc: "Tek el silahta +2 hasar." },
    { name: "Great Weapon Fighting", desc: "1-2 gelen hasar zarlarını yeniden at." },
    { name: "Interception", desc: "Yanındakinin aldığı hasarı azalt." },
    { name: "Protection", desc: "Yanındakine yapılan saldırıya dezavantaj ver." },
    { name: "Superior Technique", desc: "1 Maneuver ve 1d6 Superiority Die kazan." },
    { name: "Thrown Weapon Fighting", desc: "Fırlatılan silahlarda +2 hasar." },
    { name: "Two-Weapon Fighting", desc: "Bonus saldırıya modifier ekle." },
    { name: "Unarmed Fighting", desc: "Silahsız saldırılarda 1d6/1d8 hasar." }
];
